const cdn = "https://raw.githubusercontent.com/NJTAHJ/Bonds-Beyond-Custom-Client/main/frontend/public/";

db.card.deleteMany({ uniqueCardNumber: { $regex: "^BB1-" } });

const bb1Cards = [
  { n:"BB1-001", nm:"Koromon", c:["Red"], t:"Digi-Egg", s:"In-Training", dt:["Lesser","Nerds"], lvl:2,
    ie:"[Your Turn] [Once Per Turn] When a Digimon card with the [Nerds] trait is played, this Digimon may digivolve into a Digimon card with the [Nerds] trait in the hand with its digivolution cost reduced by 1." },
  { n:"BB1-002", nm:"Tsunomon", c:["Blue"], t:"Digi-Egg", s:"In-Training", dt:["Lesser","IADA"], lvl:2,
    ie:"[Your Turn] [Once Per Turn] When any of your Tamers with the [IADA] trait suspend, ＜Draw 1＞." },
  { n:"BB1-003", nm:"Nyaromon", c:["Yellow"], t:"Digi-Egg", s:"In-Training", dt:["Lesser","Arena"], lvl:2,
    ie:"[When Attacking] [Once Per Turn] By trashing your top or bottom security card, this digimon with the Arena trait gains +2000 DP for the turn." },
  { n:"BB1-004", nm:"Pinamon", c:["Green"], t:"Digi-Egg", s:"In-Training", dt:["Bird","DC"], lvl:2,
    ie:"[All Turns] [Once Per Turn] When any of your opponent's Tamers suspend, ＜Draw 1＞." },
  { n:"BB1-005", nm:"Dorimon", c:["Black"], t:"Digi-Egg", s:"In-Training", dt:["Lesser","X Antibody","CT"], lvl:2,
    ie:"[Your Turn] [Once Per Turn] When you play or use a Digimon or Option card with the [CT] trait, ＜Draw 1＞." },
  { n:"BB1-006", nm:"Xiaomon", c:["Purple"], t:"Digi-Egg", s:"In-Training", dt:["Lesser","Re;Ware","Girlies"], lvl:2,
    ie:"[Start of Your Main Phase] By trashing 1 card with the [Re;Ware] or [Girlies] trait in your hand, you may return 1 such card from your trash to your hand." },
  
  { n:"BB1-007", nm:"Agumon", c:["Red","Yellow"], t:"Digimon", s:"Rookie", dt:["Reptile","Nerds","IADA"], a:"Vaccine", dp:2000, pc:3, lvl:3, evo:[{color:"Red",level:2,cost:1},{color:"Yellow",level:2,cost:1}],
    sd:"[Digivolve] from Lv.2 w/[IADA] or [Nerds] trait: 0 cost",
    me:"[On Play] Reveal the top 3 cards of your deck, add one card with the [Nerds] or [IADA] trait to your hand. Send the remaining cards to the bottom of the deck.\n[Your Turn] While your opponent has a Digimon with 10000 DP or more and you have [Nathan James], this Digimon may digivolve into [WarGreymon] with the [Nerds] or [IADA] trait in your hand for a digivolution cost of 4, ignoring digivolution requirements.",
    ie:"[When Attacking] [Once Per Turn] 1 of your opponent's Digimon gets -2000 DP for the turn." },
  { n:"BB1-008", nm:"Elizamon", c:["Red","Purple"], t:"Digimon", s:"Rookie", dt:["Reptile","IADA"], a:"Virus", dp:1000, pc:3, lvl:3, evo:[{color:"Red",level:2,cost:1},{color:"Purple",level:2,cost:1}],
    sd:"[Digivolve] from Lv.2 w/[IADA] trait: 0 cost",
    me:"[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon card with the [IADA] trait and 1 Tamer card with the [IADA] trait from among them to your hand. Return the rest to the bottom of the deck.",
    ie:"[All Turns] This Digimon gets +1000 DP while it has the [IADA] trait." },
  { n:"BB1-009", nm:"Gammamon", c:["Red","Green"], t:"Digimon", s:"Rookie", dt:["Ceratopsian","Caskett"], a:"Virus", dp:2000, pc:3, lvl:3, evo:[{color:"Red",level:2,cost:0},{color:"Green",level:2,cost:0}],
    sd:"[Digivolve] from Lv.2 w/[Caskett] trait: 0 cost",
    me:"[When Moving] [On Play] Reveal the top 4 cards of your deck. Add 1 card with the [Caskett] trait and 1 Tamer card with the [Caskett] trait from among them to your hand. Return the remaining cards to the bottom of the deck.",
    ie:"[All Turns] [Once Per Turn] When a Digimon with the [Caskett] trait wins a battle, gain 1 memory." },
  { n:"BB1-010", nm:"Dracmon", c:["Red","Purple"], t:"Digimon", s:"Rookie", dt:["Undead"], a:"Virus", dp:1000, pc:3, lvl:3, evo:[{color:"Red",level:2,cost:1},{color:"Purple",level:2,cost:1}],
    sd:"[Digivolve] from Lv.2 w/[Girlies] or [Evil] trait: 0 cost",
    rule:"Treat this card as having the [Evil] trait.",
    me:"[On Play] By trashing 1 card from your hand, you may return 1 Digimon card with [Evil Dragon] in its text, or 1 Digimon card with the [Girlies] trait, from your trash to your hand.",
    ie:"[On Deletion] Gain 1 memory." },
  { n:"BB1-011", nm:"GulusGammamon", c:["Red","Purple"], t:"Digimon", s:"Champion", dt:["Dragonkin","Girlies"], a:"Virus", dp:5000, pc:5, lvl:4, evo:[{color:"Red",level:3,cost:3},{color:"Purple",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[Girlies] or [Evil] trait: 2 cost",
    rule:"Treat this card as having the [Dark Dragon] trait.",
    me:"[When Digivolving] By trashing 1 card from your hand, delete 1 of your opponent's Digimon with DP less than or equal to this Digimon's DP.",
    ie:"[On Deletion] Gain 1 memory." },
  { n:"BB1-011_P1", mn:"BB1-011", nm:"GulusGammamon", c:["Red","Purple"], t:"Digimon", s:"Champion", dt:["Dragonkin","Girlies"], a:"Virus", dp:5000, pc:5, lvl:4, evo:[{color:"Red",level:3,cost:3},{color:"Purple",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[Girlies] or [Evil] trait: 2 cost", rule:"Treat this card as having the [Dark Dragon] trait.",
    me:"[When Digivolving] By trashing 1 card from your hand, delete 1 of your opponent's Digimon with DP less than or equal to this Digimon's DP.", ie:"[On Deletion] Gain 1 memory." },
  { n:"BB1-012", nm:"Greymon", c:["Red","Yellow"], t:"Digimon", s:"Champion", dt:["Dinosaur","Nerds","IADA"], a:"Vaccine", dp:5000, pc:5, lvl:4, evo:[{color:"Red",level:3,cost:3},{color:"Yellow",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[Nerds] or [IADA] trait: 2 cost",
    me:"[On Play] [When Digivolving] You may play 1 Tamer card with the [Nerds] or [IADA] trait from your hand without paying the cost. This effect cannot play a Tamer card with the same name as any of your Tamers.except [Nathan James] Then, if you have [Nathan James], 1 of your opponent's Digimon gets -3000 DP for the turn.",
    ie:"[Your Turn] This Digimon gets +2000 DP." },
  { n:"BB1-013", nm:"BetelGammamon", c:["Red","Green"], t:"Digimon", s:"Champion", dt:["Dragonkin","Caskett"], a:"Virus", dp:5000, pc:5, lvl:4, evo:[{color:"Red",level:3,cost:2},{color:"Green",level:3,cost:2}],
    sd:"[Digivolve] from Lv.3 w/[Caskett] trait: 2 cost",
    me:"[On Play] [When Digivolving] You may suspend 1 of your opponent's Digimon with 4000 DP or less. For each Tamer with the [Caskett] trait you have in play, add 1000 to the maximum DP this effect can choose.\n[All Turns] When a Digimon becomes suspended, this Digimon may battle 1 of your opponent's Digimon.",
    ie:"[All Turns] This Digimon gets +1000 DP." },
  { n:"BB1-014", nm:"Canoweissmon", c:["Red","Green"], t:"Digimon", s:"Ultimate", dt:["Sky Dragon","Caskett"], a:"Virus", dp:8000, pc:8, lvl:5, evo:[{color:"Red",level:4,cost:4},{color:"Green",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[Caskett] trait: 3 cost",
    me:"[When Digivolving] You may suspend 1 of your opponent's Digimon. Then, you may play 1 Tamer card with the [Caskett] trait from your hand without paying its memory cost.\n[All Turns] [Once Per Turn] When any of your Tamers are played, this Digimon may battle 1 of your opponent's Digimon.\n[All Turns] When another Digimon is deleted, this Digimon may digivolve into [Gallantmon] in your hand or trash without paying its memory cost.",
    ie:"[All Turns] [Once Per Turn] When a Digimon with the [Caskett] trait wins a battle, gain 1 memory." },
  { n:"BB1-014_P1", mn:"BB1-014", nm:"Canoweissmon", c:["Red","Green"], t:"Digimon", s:"Ultimate", dt:["Sky Dragon","Caskett"], a:"Virus", dp:8000, pc:8, lvl:5, evo:[{color:"Red",level:4,cost:4},{color:"Green",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[Caskett] trait: 3 cost",
    me:"[When Digivolving] You may suspend 1 of your opponent's Digimon. Then, you may play 1 Tamer card with the [Caskett] trait from your hand without paying its memory cost.\n[All Turns] [Once Per Turn] When any of your Tamers are played, this Digimon may battle 1 of your opponent's Digimon.\n[All Turns] When another Digimon is deleted, this Digimon may digivolve into [Gallantmon] in your hand or trash without paying its memory cost.",
    ie:"[All Turns] [Once Per Turn] When a Digimon with the [Caskett] trait wins a battle, gain 1 memory." },
  { n:"BB1-015", nm:"SkullGreymon", c:["Red","Purple"], t:"Digimon", s:"Ultimate", dt:["Undead","Girlies"], a:"Virus", dp:7000, pc:7, lvl:5, evo:[{color:"Red",level:4,cost:4},{color:"Purple",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[Dark Dragon] or [Girlies] trait: 3 cost", rule:"Treat this card as having the [Evil Dragon] trait.",
    me:"[Trash] [Your Turn] When a Digimon is deleted, 1 of your Digimon with the [Dark Dragon] or [Girlies] trait may digivolve into this card in your trash.\n[On Play] [When Digivolving] By trashing 1 card in your hand, 1 of your Digimon gains ＜Raid＞ and ＜Retaliation＞ until the end of your opponent's turn. Then, 1 of your Digimon may attack a player.",
    ie:"[On Deletion] You may play 1 Level 4 or lower Digimon card with the [Evil], [Dark Dragon], or [Girlies] trait from your trash without paying the cost." },
  { n:"BB1-016", nm:"MetalGreymon", c:["Red","Black"], t:"Digimon", s:"Ultimate", dt:["Cyborg","Nerds","IADA"], a:"Vaccine", dp:7000, pc:7, lvl:5, evo:[{color:"Red",level:4,cost:4},{color:"Black",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[Nerds] or [IADA] trait: 3 cost", asm:"[Assembly\u00a0-2] Level 4 or lower Digimon card with the [Nerds] trait",
    me:"＜Blocker＞\n[When Attacking] [Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand with its play cost reduced by 2.\n[Your Turn] When another Digimon's attack ends, if this Digimon was suspended by ＜Alliance＞ for that attack, this Digimon may digivolve into a [Nerds] trait Digimon card in the hand with the cost reduced by 2.",
    ie:"＜Alliance＞" },
  { n:"BB1-017", nm:"WarGreymon", c:["Red","Yellow"], t:"Digimon", s:"Mega", dt:["Dragonkin","Nerds","IADA"], a:"Vaccine", dp:12000, pc:12, lvl:6, evo:[{color:"Red",level:5,cost:4},{color:"Yellow",level:5,cost:4}],
    sd:"[Digivolve] from Lv.5 w/[Nerds] or [IADA] trait: 3 cost",
    me:"＜Raid＞ ＜Barrier＞\n[When Digivolving] [When Attacking] Delete 1 of your opponent's lowest DP Digimon.\n[Counter] This Digimon and 1 of your other Digimon with the [Nerds] trait may DNA digivolve into a Digimon card with the [Nerds] trait in your hand.",
    ie:"＜Raid＞" },
  { n:"BB1-018", nm:"Gallantmon", c:["Red","Green"], t:"Digimon", s:"Mega", dt:["Holy Warrior","Caskett"], a:"Virus", dp:12000, pc:12, lvl:6, evo:[{color:"Red",level:5,cost:5},{color:"Green",level:5,cost:5}],
    sd:"[Digivolve] from [Barrell Caskett] while you have 3 or more Tamers w/[Caskett] trait: 5 cost",
    me:"＜Alliance＞\n[When Digivolving] You may suspend up to 2 of your opponent's Digimon. Then, this Digimon may battle 1 of your opponent's Digimon.\n[End of Attack] You may play 1 Tamer card with the [Caskett] trait from your hand or trash without paying its memory cost. Then, delete this Digimon.\n[All Turns] This Digimon gets +2000 DP for each of your Tamers with different names." },
  { n:"BB1-019", nm:"MagnaKidmon", c:["Red"], t:"Digimon", s:"Mega", dt:["Dragonkin","IADA"], a:"Virus", dp:11000, pc:11, lvl:6, evo:[{color:"Red",level:5,cost:3}],
    sd:"[Digivolve] from Lv.5 w/[IADA] trait: 3 cost", xros:"[DigiXros\u00a0-2] 2 Lv.5 or lower Digimon cards with the [IADA] trait and different levels",
    me:"＜Rush＞ ＜Raid＞\n[On Play] [When Attacking] Delete 1 of your opponent's lowest DP Digimon. If this effect didn't delete, 1 of your Digimon with the [IADA] trait is unaffected by your opponent's Option cards and its DP cannot be reduced until the end of your opponent's turn.\n[All Turns] For each of your Tamers with the [IADA] trait and different names, this Digimon gets +1000 DP." },
  { n:"BB1-019_P1", mn:"BB1-019", nm:"MagnaKidmon", c:["Red"], t:"Digimon", s:"Mega", dt:["Dragonkin","IADA"], a:"Virus", dp:11000, pc:11, lvl:6, evo:[{color:"Red",level:5,cost:3}],
    sd:"[Digivolve] from Lv.5 w/[IADA] trait: 3 cost", xros:"[DigiXros\u00a0-2] 2 Lv.5 or lower Digimon cards with the [IADA] trait and different levels",
    me:"＜Rush＞ ＜Raid＞\n[On Play] [When Attacking] Delete 1 of your opponent's lowest DP Digimon. If this effect didn't delete, 1 of your Digimon with the [IADA] trait is unaffected by your opponent's Option cards and its DP cannot be reduced until the end of your opponent's turn.\n[All Turns] For each of your Tamers with the [IADA] trait and different names, this Digimon gets +1000 DP." },
  { n:"BB1-020", nm:"Megidramon", c:["Red","Purple"], t:"Digimon", s:"Mega", dt:["Evil Dragon","Four Great Dragons","Girlies"], a:"Virus", dp:13000, pc:13, lvl:6, evo:[{color:"Red",level:5,cost:6},{color:"Purple",level:5,cost:6}],
    sd:"[Digivolve] from Lv.5 w/[Evil Dragon] or [Girlies] trait: 5 cost", rule:"Treat this card as having the name [ChaosGallantmon].",
    me:"[Trash] [Your Turn] When a Digimon is deleted, 1 of your Digimon with the [Dark Dragon] or [Girlies] trait may digivolve into this card in your trash with its digivolution cost reduced by 2.\n[On Play] [When Digivolving] [On Deletion] By trashing 1 card in your hand, delete all of your opponent's lowest DP Digimon.\n[All Turns] [Once Per Turn] When a Digimon is deleted, you may play 1 Level 4 or lower Digimon card with the [Evil], [Dark Dragon], or [Girlies] trait from your trash without paying the cost." },
  { n:"BB1-021", nm:"MedievalGallantmon", c:["Red","Green"], t:"Digimon", s:"Mega", dt:["Warrior","Caskett"], a:"Virus", dp:15000, pc:15, lvl:7, evo:[{color:"Red",level:6,cost:6},{color:"Green",level:6,cost:6}],
    sd:"[Digivolve] from [Barrell Caskett] while you have 3 or more Tamers w/[Caskett] trait: 5 cost",
    me:"When this card would be played, reduce the play cost by 2 for each of your Tamers with the [Caskett] trait and different names.\n＜Rush＞ ＜Alliance＞ ＜Piercing＞\n[On Play] [When Digivolving] You may suspend up to 2 Digimon. Then, you may delete 1 of your opponent's Digimon with 8000 DP or less. For each of your Tamers with the [Caskett] trait and different names, add 2000 to the maximum DP this effect can delete.\n[All Turns] [Once Per Turn] When any of your Tamers are played, 1 of your Digimon with the [Caskett] trait may battle 1 of your opponent's Digimon.\n[All Turns] If this Digimon would leave the battle area other than by your effects, you may play 1 [Barrell Caskett] from this Digimon's digivolution cards without paying its memory cost." },
  { n:"BB1-022", nm:"Gaossmon", c:["Blue"], t:"Digimon", s:"Rookie", dt:["Reptile"], a:"Virus", dp:3000, pc:3, lvl:3, evo:[{color:"Blue",level:2,cost:0}],
    sd:"[Digivolve] from [Koromon]: 0 cost",
    me:"[Your Turn] When this Digimon would digivolve into a [Blue] Digimon card with [Greymon] in its name, reduce the digivolution cost by 1.", ie:"＜Jamming＞" },
  { n:"BB1-023", nm:"Gaomon", c:["Blue","Black"], t:"Digimon", s:"Rookie", dt:["Beast","Girlies","IADA"], a:"Data", dp:2000, pc:3, lvl:3, evo:[{color:"Blue",level:2,cost:1},{color:"Black",level:2,cost:1}],
    sd:"[Digivolve] from Lv.2 w/[Girlies] or [IADA] trait: 0 cost",
    me:"＜Blocker＞\n[On Play] [On Deletion] You may return 1 card with the [Girlies] or [IADA] trait from your trash to your hand.", ie:"＜Reboot＞" },
  { n:"BB1-024", nm:"Gabumon", c:["Blue","Green"], t:"Digimon", s:"Rookie", dt:["Reptile","Nerds","IADA"], a:"Data", dp:2000, pc:3, lvl:3, evo:[{color:"Blue",level:2,cost:1},{color:"Green",level:2,cost:1}],
    sd:"[Digivolve] from Lv.2 w/[Nerds] or [IADA] trait: 0 cost",
    me:"[On Play] By trashing 1 card with the [Nerds] or [IADA] trait from your hand, ＜Draw 2＞.\n[Your Turn] While your opponent has a Digimon with 10000 DP or more and you have [Nathan James], this Digimon may digivolve into [MetalGarurumon] with the [Nerds] or [IADA] trait in your hand for a digivolution cost of 4, ignoring digivolution requirements.",
    ie:"[When Attacking] [Once Per Turn] If you have 7 or fewer cards in your hand, ＜Draw 1＞." },
  { n:"BB1-025", nm:"Gabumon", c:["Blue","Black"], t:"Digimon", s:"Rookie", dt:["Reptile","IADA"], a:"Data", dp:2000, pc:3, lvl:3, evo:[{color:"Blue",level:2,cost:1},{color:"Black",level:2,cost:1}],
    sd:"[Digivolve] from Lv.2 w/[IADA] trait: 0 cost",
    me:"[Start of Your Main Phase] If you have a Tamer with the [IADA] trait, gain 1 memory and ＜Draw 1＞.",
    ie:"[Your Turn] [Once Per Turn] When a Tamer card with the [IADA] trait is played, ＜Draw 1＞." },
  { n:"BB1-026", nm:"Garurumon", c:["Blue","Green"], t:"Digimon", s:"Champion", dt:["Beast","Nerds","IADA"], a:"Data", dp:5000, pc:5, lvl:4, evo:[{color:"Blue",level:3,cost:3},{color:"Green",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[Nerds] or [IADA] trait: 2 cost",
    me:"[On Play] [When Digivolving] You may play 1 Tamer card with the [Nerds] or [IADA] trait from your hand without paying the cost. This effect cannot play a Tamer card with the same name as any of your Tamers, except [Nathan James] Then, if you have [Nathan James], 1 of your opponent's Digimon or Tamers cannot unsuspend during their next unsuspend phase.",
    ie:"[Your Turn] [Once Per Turn] When a Digimon card with the [IADA] or [Nerds] trait is played, ＜Draw 1＞." },
  { n:"BB1-027", nm:"Garurumon", c:["Blue","Black"], t:"Digimon", s:"Champion", dt:["Beast","IADA"], a:"Vaccine", dp:5000, pc:5, lvl:4, evo:[{color:"Blue",level:3,cost:3},{color:"Black",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[IADA] trait: 2 cost",
    me:"[On Play] [When Digivolving] You may play 1 Tamer card with the [IADA] trait from your hand without paying the cost. This effect cannot play a Tamer card with the same name as any of your Tamers, except [Director Watanabe] Then, if you have [Director Watanabe], ＜Draw 1＞.",
    ie:"[Your Turn] [Once Per Turn] When a Tamer card with the [IADA] trait is played, ＜Draw 1＞." },
  { n:"BB1-028", nm:"Greymon", c:["Blue"], t:"Digimon", s:"Champion", dt:["Dinosaur"], a:"Virus", dp:5000, pc:5, lvl:4, evo:[{color:"Blue",level:3,cost:2}],
    sd:"[Digivolve] 2 from Blue [Gaossmon]",
    me:"[On Play] [When Digivolving] You may reveal the top 4 cards of your deck. Add 1 [Blue] Digimon card with [Greymon] in its name and 1 [Laura Loath] from among them to your hand. Return the rest to the bottom of the deck.",
    ie:"[All Turns] [Once Per Turn] If a Digimon is deleted, you may play 1 [Laura Loath] from your hand without paying the cost." },
  { n:"BB1-029", nm:"Sangloupmon", c:["Blue","Black"], t:"Digimon", s:"Champion", dt:["Dark Animal","Girlies","IADA"], a:"Virus", dp:5000, pc:5, lvl:4, evo:[{color:"Blue",level:3,cost:3},{color:"Black",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[Girlies] or [IADA] trait: 2 cost",
    me:"＜Blocker＞\n[On Play] [When Digivolving] ＜Draw 1＞. Then, if you have [Kazuo Kubo], until the end of your opponent's turn, 1 of their Digimon gains \"[Start of Your Main Phase] This Digimon attacks.\"",
    ie:"＜Reboot＞" },
  { n:"BB1-030", nm:"Cyberdramon", c:["Blue","Black"], t:"Digimon", s:"Ultimate", dt:["Cyborg","Girlies","IADA"], a:"Vaccine", dp:7000, pc:7, lvl:5, evo:[{color:"Blue",level:4,cost:4},{color:"Black",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[Girlies] or [IADA] trait: 3 cost",
    me:"＜Blocker＞\n[Hand] [All Turns] When 1 of your Digimon with the [Girlies] or [IADA] trait would be deleted by battle, by digivolving it into this card without paying the cost, prevent that deletion. If you digivolved by this effect, trash that Digimon's top stacked card at the end of your turn.\n[When Digivolving] This Digimon may unsuspend. Then, if digivolved by [Cyberdramon]'s effect, or if you have [Kazuo Kubo], ＜De-Digivolve 1＞ 1 of your opponent's Digimon.",
    ie:"[All Turns] [Once Per Turn] When attack targets change, ＜De-Digivolve 1＞ 1 of your opponent's Digimon." },
  { n:"BB1-031", nm:"MetalGreymon", c:["Blue"], t:"Digimon", s:"Ultimate", dt:["Cyborg"], a:"Virus", dp:7000, pc:7, lvl:5, evo:[{color:"Blue",level:4,cost:4}],
    sd:"[Digivolve] from [Blue] [Greymon]: 3 cost",
    me:"[On Play] [When Digivolving] You may suspend up to 2 of your opponent's Digimon with DP less than or equal to this Digimon's DP. Then, if it is your turn, you may delete 1 of your opponent's suspended Digimon.\n[All Turns] [Once Per Turn] When any Option cards are used, gain 1 memory.\n[All Turns] While you have [Laura Loath], this Digimon gets +3000 DP and ＜Piercing＞.",
    ie:"[Your Turn] [Once Per Turn] When you use a [Blue] Option card with [Greymon] in its text, return 1 of your opponent's lowest DP Digimon to the bottom of the deck." },
  { n:"BB1-032", nm:"MetalMamemon", c:["Blue","Black"], t:"Digimon", s:"Ultimate", dt:["Cyborg","IADA"], a:"Data", dp:7000, pc:7, lvl:5, evo:[{color:"Blue",level:4,cost:4},{color:"Black",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[IADA] trait: 3 cost",
    me:"[On Play] [When Digivolving] For each of your Tamers with the [IADA] trait and different names, trash 1 digivolution card from any of your opponent's Digimon. Then, return 1 of their Digimon with 1 or fewer digivolution cards to the hand.\n[Your Turn] [Once Per Turn] When any of your Tamers with the [IADA] trait are played, you may unsuspend this Digimon.",
    ie:"[Your Turn] [Once Per Turn] When any of your Tamers with the [IADA] trait suspend or are played, ＜De-Digivolve 1＞ 1 of your opponent's Digimon." },
  { n:"BB1-033", nm:"WereGarurumon", c:["Blue","Green"], t:"Digimon", s:"Ultimate", dt:["Beastkin","Nerds","IADA"], a:"Vaccine", dp:7000, pc:7, lvl:5, evo:[{color:"Blue",level:4,cost:4},{color:"Green",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[Nerds] or [IADA] trait: 3 cost", asm:"[Assembly\u00a0-2] Level 4 or lower Digimon card with the [Nerds] trait",
    me:"＜Evade＞\n[When Attacking] [Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your trash with its play cost reduced by 2.\n[Your Turn] When another Digimon's attack ends, if this Digimon was suspended by ＜Alliance＞ for that attack, this Digimon may digivolve into a [Nerds] trait Digimon card in the hand with the cost reduced by 2.",
    ie:"＜Alliance＞" },
  { n:"BB1-034", nm:"ShineGreymon", c:["Blue"], t:"Digimon", s:"Mega", dt:["Light Dragon"], a:"Virus", dp:12000, pc:12, lvl:6, evo:[{color:"Blue",level:5,cost:4}],
    sd:"[Digivolve] from [Blue] [MetalGreymon]: 3 cost / [ZeigGreymon]: 1 cost", asm:"[Assembly\u00a0-5] [Blue] [Greymon] x [Laura Loath]",
    me:"＜Blocker＞ ＜Piercing＞\n[On Play] [When Digivolving] If [Laura Loath] is not in this Digimon's digivolution cards, you may place 1 [Laura Loath] from your hand or battle area under this Digimon as its bottom digivolution card. Then, you may delete 1 of your opponent's lowest play cost Digimon.\n[All Turns] When this card would leave the battle area, you may play 1 [Laura Loath] and 1 Level 4 [Blue] [Greymon] from this Digimon's digivolution cards without paying the costs." },
  { n:"BB1-035", nm:"Metatromon", c:["Blue","Black"], t:"Digimon", s:"Mega", dt:["Machine","IADA"], a:"Vaccine", dp:13000, pc:13, lvl:6, evo:[{color:"Blue",level:5,cost:5},{color:"Black",level:5,cost:5}],
    sd:"[Digivolve] from Lv.5 w/[IADA] trait: 4 cost",
    me:"When any of your [MetalMamemon] would digivolve into this card, reduce the digivolution cost by 1 for every 2 of your Tamers with the [IADA] trait and different names.\n＜Blocker＞ ＜Decode ([MetalMamemon])＞\n[When Digivolving] [When Attacking] [Once Per Turn] You may play 1 Tamer card with the [IADA] trait from your hand or trash without paying the cost.Then, if you have [Director Watanabe], return 1 of your opponent's lowest play cost Digimon to the bottom of the deck.\n[All Turns] [Once Per Turn] When any of your Tamers with the [IADA] trait are played or become suspended, 1 of your opponent's Digimon cannot unsuspend until the end of their turn." },
  { n:"BB1-036", nm:"MetalGarurumon", c:["Blue","Green"], t:"Digimon", s:"Mega", dt:["Cyborg","Nerds","IADA"], a:"Data", dp:12000, pc:12, lvl:6, evo:[{color:"Blue",level:5,cost:4},{color:"Green",level:5,cost:4}],
    sd:"[Digivolve] from Lv.5 w/[Nerds] or [IADA] trait: 3 cost",
    me:"＜Piercing＞ ＜Evade＞\n[When Digivolving] [When Attacking] Return 1 of your opponent's lowest level Digimon to the bottom of the deck.\n[End of Your Turn] This Digimon and 1 of your other Digimon with the [Nerds] trait may DNA digivolve into a Digimon card with the [Nerds] trait in your hand.",
    ie:"＜Piercing＞" },
  { n:"BB1-037", nm:"ShineGreymon: Burst Mode/Ride The Lightning", c:["Blue","Yellow"], t:"Digimon/Option", s:"Mega", dt:["Light Dragon"], a:"Virus", dp:15000, pc:15, lvl:7, evo:[{color:"Blue",level:6,cost:5},{color:"Yellow",level:6,cost:5}],
    sd:"[Digivolve] from Blue Lv.6 w/[Greymon] in name: 5 cost",
    me:"＜Security A. +1＞ ＜Reboot＞ ＜Blocker＞ ＜Piercing＞\n[When Digivolving] ＜Counter＞ [Once Per Turn] You may activate 1 [Main] effect on this card's Option side. Then, you may place 1 [Laura Loath] from your hand or trash under this Digimon as its bottom digivolution card.\n[End of Attack] [Once Per Turn] Unsuspend this Digimon. Then, trash 4 digivolution cards from under 1 of your opponent's Digimon.\n[All Turns] If this Digimon would leave the battle area, you may play 1 [Laura Loath] and 1 Level 4 [Blu.] [Greymon] from this Digimon's digivolution cards without paying their memory costs.",
    de:"[Arts Digivolve]",
    ocolor:"Blue",
    oef:"[Main] 1 of your opponent's Digimon gets -3000 DP for each Option card in the battle area and trash for the turn. Then, 2 of your opponent's Digimon cannot suspend until the end of their turn." },
  
  { n:"BB1-038", nm:"Kotemon", c:["Yellow","Black"], t:"Digimon", s:"Rookie", dt:["Reptile","DC"], a:"Data", dp:2000, pc:3, lvl:3, evo:[{color:"Yellow",level:2,cost:1}],
    sd:"[Digivolve] from Lv.2 w/[DC] trait: 0 cost",
    me:"[On Play] Reveal the top 3 cards of your deck. Add 1 [DC] trait Digimon, Option, or Tamer card from among them to your hand. Return the rest to the bottom of the deck.",
    ie:"＜Reboot＞" },
  { n:"BB1-039", nm:"Salamon", c:["Yellow","Green"], t:"Digimon", s:"Rookie", dt:["Mammal","Arena"], a:"Vaccine", dp:2000, pc:3, lvl:3, evo:[{color:"Yellow",level:2,cost:1},{color:"Green",level:2,cost:1}],
    sd:"[Digivolve] from Lv.2 w/[Arena] trait: 0 cost",
    me:"[On Play] [When Moving] This Digimon gets +3000 DP and ＜Piercing＞ for the turn.",
    ie:"[All Turns] This Digimon gets +1000 DP." },
  { n:"BB1-040", nm:"Wankomon", c:["Yellow"], t:"Digimon", s:"Rookie", dt:["Beast","IADA"], a:"Data", dp:2000, pc:3, lvl:3, evo:[{color:"Yellow",level:2,cost:0}],
    sd:"[Digivolve] from Lv.2 w/[IADA] trait: 0 cost",
    me:"[Your Turn] When this Digimon would digivolve into a Digimon card with the [IADA] trait, reduce the digivolution cost by 1.",
    ie:"[All Turns] [Once Per Turn] When any of your Tamers with the [IADA] trait becomes suspended, 1 of your opponent's Digimon gets -2000 DP for the turn." },
  { n:"BB1-041", nm:"Sistermon Ciel", c:["Yellow"], t:"Digimon", s:"Champion", dt:["Puppet","DC"], a:"Vaccine", dp:5000, pc:5, lvl:4, evo:[{color:"Yellow",level:3,cost:2}],
    sd:"[Digivolve] from Lv.3 w/[DC] trait: 2 cost",
    me:"[When Digivolving] You may play 1 Tamer card with the [DC] trait from your hand without paying the cost. For the turn, the Tamer played by this effect is also treated as a 4000 DP Digimon and cannot digivolve.",
    ie:"＜Alliance＞" },
  { n:"BB1-042", nm:"Fangmon", c:["Yellow","Purple"], t:"Digimon", s:"Champion", dt:["Dark Animal","IADA"], a:"Data", dp:5000, pc:5, lvl:4, evo:[{color:"Yellow",level:3,cost:3},{color:"Purple",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[IADA] trait: 2 cost",
    me:"[When Digivolving] [When Attacking] [Once Per Turn] If it is your turn, by trashing 1 card with the [IADA] trait in your hand, you may play 1 card with the [IADA] trait from your hand or trash with its play cost reduced by 3.\n[All Turns] While you have [Dane Cathal], this Digimon has ＜Guard＞.",
    ie:"[All Turns] [Once Per Turn] When any of your Tamers with the [IADA] trait becomes suspended, 1 of your opponent's Digimon gets -2000 DP for the turn." },
  { n:"BB1-043", nm:"Lynxmon", c:["Yellow","Red"], t:"Digimon", s:"Champion", dt:["Beast","Arena"], a:"Free", dp:6000, pc:6, lvl:4, evo:[{color:"Yellow",level:3,cost:3},{color:"Red",level:3,cost:3}],
    sd:"[Digivolve] from [Salamon] or Lv.3 w/[Arena] trait: 2 cost",
    me:"＜Armor Purge＞ ＜Barrier＞\n[End of Attack] [Once Per Turn] This Digimon may digivolve into a Digimon card with the [Arena], [Angel], or [Holy Beast] trait in your hand with its digivolution cost reduced by 2." },
  { n:"BB1-044", nm:"Kyukimon", c:["Yellow","Black"], t:"Digimon", s:"Ultimate", dt:["Mysterious Beast","DC"], a:"Virus", dp:7000, pc:7, lvl:5, evo:[{color:"Yellow",level:4,cost:4},{color:"Black",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[DC] trait: 3 cost",
    me:"＜Collision＞\n[On Play] [When Digivolving] For the turn, 1 Tamer is also treated as a 4000 DP Digimon and cannot digivolve.",
    ie:"[All Turns] [Once Per Turn] When a Tamer becomes suspended, unsuspend this Digimon." },
  { n:"BB1-045", nm:"Caturamon", c:["Yellow","Purple"], t:"Digimon", s:"Ultimate", dt:["Holy Beast","IADA"], a:"Data", dp:7000, pc:7, lvl:5, evo:[{color:"Yellow",level:4,cost:4},{color:"Purple",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[IADA] trait: 3 cost",
    me:"＜Blocker＞\n[When Digivolving] [When Attacking] For each of your Digimon and Tamers with the [IADA] trait, 1 of your opponent's Digimon gets -1000 DP for the turn.\n[All Turns] While you have [Dane Cathal], this Digimon has ＜Reboot＞.",
    ie:"[Your Turn] [Once Per Turn] When any of your Tamers with the [IADA] trait suspend, if you have 3 or fewer security cards, ＜Recovery +1＞." },
  { n:"BB1-046", nm:"Mihiramon", c:["Yellow","Green"], t:"Digimon", s:"Ultimate", dt:["Holy Beast","Arena"], a:"Data", dp:7000, pc:7, lvl:5, evo:[{color:"Yellow",level:4,cost:4},{color:"Green",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[Arena] trait: 3 cost",
    me:"[On Play] [When Digivolving] Suspend 1 of your opponent's Digimon. Then, by trashing your top or bottom security card, 1 of your opponent's Digimon gets -3000 DP until the end of the turn.\n[Your Turn] When this Digimon wins a battle, this Digimon may digivolve into a Digimon card with the [Arena] trait in your hand with its digivolution cost reduced by 2.",
    ie:"[All Turns] [Once Per Turn] When this Digimon wins a battle, unsuspend this Digimon." },
  { n:"BB1-047", nm:"Anubismon", c:["Yellow","Purple"], t:"Digimon", s:"Mega", dt:["Shaman","IADA"], a:"Vaccine", dp:12000, pc:12, lvl:6, evo:[{color:"Yellow",level:5,cost:4},{color:"Purple",level:5,cost:4}],
    sd:"[Digivolve] from Lv.5 w/[IADA] trait: 3 cost",
    me:"＜Scapegoat＞\n[When Digivolving] [End of Your Turn] [Once Per Turn] You may play 1 Level 4 or lower Digimon card with the [IADA] trait from your trash without paying the cost.\n[All Turns] When you play another Digimon with the [IADA] trait, all of your Digimon with the [IADA] trait gain ＜Blocker＞ until the end of your opponent's turn." },
  { n:"BB1-047_P1", mn:"BB1-047", nm:"Anubismon", c:["Yellow","Purple"], t:"Digimon", s:"Mega", dt:["Shaman","IADA"], a:"Vaccine", dp:12000, pc:12, lvl:6, evo:[{color:"Yellow",level:5,cost:4},{color:"Purple",level:5,cost:4}],
    sd:"[Digivolve] from Lv.5 w/[IADA] trait: 3 cost",
    me:"＜Scapegoat＞\n[When Digivolving] [End of Your Turn] [Once Per Turn] You may play 1 Level 4 or lower Digimon card with the [IADA] trait from your trash without paying the cost.\n[All Turns] When you play another Digimon with the [IADA] trait, all of your Digimon with the [IADA] trait gain ＜Blocker＞ until the end of your opponent's turn." },
  { n:"BB1-048", nm:"Beautymon", c:["Yellow","Black"], t:"Digimon", s:"Mega", dt:["Beauty","DC"], a:"Virus", dp:12000, pc:11, lvl:6, evo:[{color:"Yellow",level:5,cost:4},{color:"Black",level:5,cost:4}],
    sd:"[Digivolve] from Lv.5 w/[DC] trait: 3 cost",
    me:"＜Collision＞ ＜Blocker＞\n[On Play] [When Digivolving] [When Attacking] [Once Per Turn] Until the end of your opponent's turn, 1 Tamer is also treated as a 4000 DP Digimon and cannot digivolve.\n[All Turns] Your Tamers with the [DC] trait get +6000 DP and gain ＜Blocker＞.\n[Opponent's Turn] [Once Per Turn] When a Tamer is played, for the turn, 1 of your opponent's Tamers is also treated as a 4000 DP Digimon and cannot digivolve. Then, 1 of your opponent's Digimon attacks." },
  { n:"BB1-049", nm:"LovelyAngemon", c:["Yellow","Black"], t:"Digimon", s:"Mega", dt:["Warrior","Arena"], a:"Vaccine", dp:12000, pc:12, lvl:6, evo:[{color:"Yellow",level:5,cost:5},{color:"Black",level:5,cost:5}],
    sd:"[Digivolve] from Lv.5 w/[Arena] trait: 4 cost",
    me:"＜Collision＞ ＜Barrier＞ ＜Piercing＞ ＜Blocker＞\n[All Turns] [Once Per Turn] When this Digimon would leave the battle area other than by battle, by trashing your top security card, it does not leave.\n[All Turns] [Once Per Turn] When a card is removed from your security stack, this Digimon gets +3000 DP until the end of your opponent's turn. Then, this Digimon may battle 1 of your opponent's Digimon." },
  
  { n:"BB1-050", nm:"Aruraumon", c:["Green","Yellow"], t:"Digimon", s:"Rookie", dt:["Vegetation","Nerds","IADA"], a:"Data", dp:2000, pc:3, lvl:3, evo:[{color:"Green",level:2,cost:0},{color:"Yellow",level:2,cost:0}],
    sd:"[Digivolve] from Lv.2 w/[Nerds] or [IADA] trait: 0 cost",
    me:"[On Play] [When Moving] By trashing 1 card with the [Nerds] or [IADA] trait from your hand, ＜Draw 2＞.\n[Your Turn] While you have [Oryon Sonier], this Digimon gets +2000 DP.",
    ie:"[Your Turn] This Digimon gets +2000 DP." },
  { n:"BB1-051", nm:"Falcomon", c:["Green","Purple"], t:"Digimon", s:"Rookie", dt:["Avian","DC"], a:"Vaccine", dp:2000, pc:3, lvl:3, evo:[{color:"Green",level:2,cost:1},{color:"Purple",level:2,cost:1}],
    sd:"[Digivolve] from Lv.2 w/[DC] trait: 0 cost",
    me:"[Your Turn] When a Tamer becomes suspended, this Digimon may digivolve into a [Crowmon] in your hand for a digivolution cost of 3, ignoring digivolution requirements.",
    ie:"[Your Turn] [Once Per Turn] When an opponent's Tamer becomes suspended, gain 1 memory." },
  { n:"BB1-052", nm:"Pteromon", c:["Green"], t:"Digimon", s:"Rookie", dt:["Bird Dragon","Arena","IADA"], a:"Data", dp:2000, pc:3, lvl:3, evo:[{color:"Green",level:2,cost:0}],
    sd:"[Digivolve] from Lv.2 w/[Arena] or [IADA] trait: 0 cost",
    me:"[When Moving] [On Play] You may suspend 1 Digimon. If this effect suspended this Digimon, this Digimon may digivolve into a Digimon card with the [Arena] or [IADA] trait in your hand without paying the cost.",
    ie:"[All Turns] While this Digimon is suspended, it gets +2000 DP." },
  { n:"BB1-053", nm:"Wormmon", c:["Green","Purple"], t:"Digimon", s:"Rookie", dt:["Larva","Arena","Nerds"], a:"Free", dp:2000, pc:3, lvl:3, evo:[{color:"Green",level:2,cost:1},{color:"Purple",level:2,cost:1}],
    sd:"[Digivolve] from [Minomon] or Lv.2 w/[Nerds] or [Arena] trait: 0 cost",
    me:"[All Turns] When 1 of your Digimon wins a battle, this Digimon may digivolve into a Digimon card with the [Nerds] or [Arena] trait in your trash without paying its digivolution cost.",
    ie:"[When Attacking] [Once Per Turn] Suspend 1 of your opponent's Digimon." },
  { n:"BB1-054", nm:"Galemon", c:["Green"], t:"Digimon", s:"Champion", dt:["Bird Dragon","Arena","IADA"], a:"Data", dp:4000, pc:5, lvl:4, evo:[{color:"Green",level:3,cost:2}],
    sd:"[Digivolve] from Lv.3 w/[Arena] or [IADA] trait: 2 cost",
    me:"[When Attacking] Suspend 1 Digimon. Then, if attacking an opponent's Digimon, or if you have [Orla Mallon], this Digimon may digivolve into a Digimon card with the [Arena] or [IADA] trait in your hand with its digivolution cost reduced by 1.",
    ie:"[All Turns] While this Digimon is suspended, it gets +2000 DP." },
  { n:"BB1-055", nm:"Weedmon", c:["Green","Yellow"], t:"Digimon", s:"Champion", dt:["Vegetation","Nerds","IADA"], a:"Virus", dp:5000, pc:5, lvl:4, evo:[{color:"Green",level:3,cost:3},{color:"Yellow",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[Nerds] or [IADA] trait: 2 cost",
    me:"[On Play] [When Digivolving] Suspend 1 of your opponent's Digimon. Then, if you have [Oryon Sonier], that Digimon cannot unsuspend during your opponent's next unsuspend phase.\n[Your Turn] While you have [Oryon Sonier], all of your Digimon with the [IADA] or [Nerds] trait gain ＜Piercing＞.",
    ie:"[Your Turn] [Once Per Turn] When an opponent's Digimon becomes suspended, gain 1 memory." },
  { n:"BB1-056", nm:"Stingmon", c:["Green","Purple"], t:"Digimon", s:"Champion", dt:["Insectoid","Arena","Nerds"], a:"Free", dp:4000, pc:5, lvl:4, evo:[{color:"Green",level:3,cost:2},{color:"Purple",level:3,cost:2}],
    sd:"[Digivolve] from Lv.3 w/[Arena] or [Nerds] trait: 2 cost",
    me:"[When Attacking] If this Digimon attacks an opponent's Digimon, this Digimon may digivolve into a Digimon card with the [Arena] or [Nerds] trait in your trash with its digivolution cost reduced by 1.",
    ie:"[When Attacking] [Once Per Turn] Suspend 1 of your opponent's Digimon." },
  { n:"BB1-057", nm:"Peckmon", c:["Green","Purple"], t:"Digimon", s:"Champion", dt:["Avian","DC"], a:"Vaccine", dp:4000, pc:4, lvl:4, evo:[{color:"Green",level:3,cost:3},{color:"Purple",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[DC] trait: 2 cost",
    me:"[On Play] [When Digivolving] Suspend 1 of your opponent's Tamers. Then, if your opponent has no unsuspended Tamers, trash the top 2 cards of their deck.",
    ie:"[Your Turn] [Once Per Turn] When an opponent's Tamer becomes suspended, gain 1 memory." },
  { n:"BB1-058", nm:"Dinobeemon (X Antibody)", c:["Green","Purple"], t:"Digimon", s:"Ultimate", dt:["Mutant","Free","Arena","Nerds","X Antibody"], a:"Free", dp:8000, pc:8, lvl:5, evo:[{color:"Green",level:4,cost:5},{color:"Purple",level:4,cost:5}],
    sd:"[Digivolve] from [Dinobeemon]: 0 cost / Lv.4 w/[Nerds] or [Arena] trait: 4 cost", rule:"Treat this card as also having the [Insectoid] and [Mythical Dragon] traits.",
    me:"＜Vortex＞\n[When Digivolving] Suspend 1 of your opponent's Digimon or Tamers. Then, if [Dinobeemon] is in this Digimon's digivolution cards or it digivolved from the trash, you may play 1 Level 3 or lower Digimon card with the [Nerds] or [Arena] trait from your trash without paying the cost.",
    ie:"[Your Turn] [Once Per Turn] When this Digimon attacks an opponent's Digimon, you may play 1 Level 3 or lower Digimon card with the [Nerds], [Arena], or [Free] trait from your trash without paying the cost." },
  { n:"BB1-059", nm:"The Raven", c:["Green","Purple"], t:"Digimon", s:"Ultimate", dt:["Avian","DC"], a:"Vaccine", dp:7000, pc:7, lvl:5, evo:[{color:"Green",level:4,cost:3},{color:"Purple",level:4,cost:3}],
    sd:"[Digivolve] from Lv.4 w/[DC] trait: 3 cost", rule:"Treat this card as having the name [Crowmon].",
    me:"＜Fortitude＞\n[On Play] [When Digivolving] Suspend 1 of your opponent's Tamers. Then, 1 of your opponent's Tamers cannot unsuspend until the end of your opponent's turn.\n[All Turns] [Once Per Turn] When an opponent's Tamer becomes suspended, you may trash the top card of your opponent's deck for every 2 of their suspended Tamers.",
    ie:"[All Turns] [Once Per Turn] When an opponent's Tamer becomes suspended, trash your opponent's top security card." },
  { n:"BB1-060", nm:"Lilamon", c:["Green","Yellow"], t:"Digimon", s:"Ultimate", dt:["Fairy","Nerds","IADA"], a:"Data", dp:7000, pc:7, lvl:5, evo:[{color:"Green",level:4,cost:4},{color:"Yellow",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[Nerds] or [IADA] trait: 3 cost",
    me:"[When Digivolving] Suspend 1 of your opponent's Digimon. That Digimon cannot unsuspend during your opponent's next unsuspend phase.\n[When Attacking] If you have [Oryon Sonier], this Digimon may digivolve into a [Nerds] or [IADA] trait Digimon card in the hand with the cost reduced by 2.",
    ie:"[Your Turn] While this Digimon is Level 6 or higher and has the [Nerds] or [IADA] trait, it gets +2000 DP and ＜Piercing＞." },
  { n:"BB1-061", nm:"GranKuwagamon", c:["Green","Purple"], t:"Digimon", s:"Mega", dt:["Insectoid","Arena","Nerds"], a:"Free", dp:12000, pc:11, lvl:6, evo:[{color:"Green",level:5,cost:4},{color:"Purple",level:5,cost:4}],
    sd:"[Digivolve] from Lv.5 w/[Dinobeemon] in its name or w/[Nerds] or [Arena] trait: 3 cost",
    me:"＜Armor Purge＞ ＜Piercing＞\n[When Digivolving] Play 1 Level 4 or lower Digimon card with the [Nerds] or [Arena] trait from your trash without paying the cost, or play 1 [Drone] Token to your opponent's field suspended (Digimon/Lv.1/Green/Insectoid/2000 DP/This Digimon cannot unsuspend. [On Deletion] Suspend 1 of your Digimon). Then, by placing 1 [GrandisKuwagamon] from your trash as this Digimon's top digivolution card, this Digimon may attack.\n[End of Attack] By placing this Digimon's top stacked card as its bottom digivolution card, unsuspend this Digimon." },

  { n:"BB1-062", nm:"Psychemon", c:["Black","Blue"], t:"Digimon", s:"Rookie", dt:["Reptile","CT"], a:"Virus", dp:2000, pc:3, lvl:3, evo:[{color:"Black",level:2,cost:1},{color:"Blue",level:2,cost:1}],
    sd:"[Digivolve] from Lv.2 w/[CT] trait: 0 cost",
    me:"[On Play] Reveal the top 3 cards of your deck. Add 1 card with the [CT] trait from among them to your hand. Trash the rest.",
    ie:"[Your Turn] [Once Per Turn] When you would play or use a Digimon or Option card with the [CT] trait, reduce the cost by 1." },
  { n:"BB1-063", nm:"Junkmon", c:["Black"], t:"Digimon", s:"Rookie", dt:["Puppet","ME"], a:"Virus", dp:2000, pc:3, lvl:3, evo:[{color:"Black",level:2,cost:0}],
    sd:"[Digivolve] from Lv.2 w/[ME] trait: 0 cost",
    me:"[Start of Your Main Phase] By trashing 1 card with the [ME] trait from your hand, this Digimon may digivolve into a Digimon card with the [ME] trait in your hand without paying its digivolution cost.",
    ie:"[When Attacking] [Once Per Turn] Reveal the top 3 cards of your deck. For each card with the [ME] trait, this Digimon gets +1000 DP until the end of your opponent's turn. Return the rest to the top or bottom of the deck." },
  { n:"BB1-064", nm:"ToyAgumon", c:["Black"], t:"Digimon", s:"Rookie", dt:["Puppet"], a:"Vaccine", dp:2000, pc:3, lvl:3, evo:[{color:"Black",level:2,cost:0}],
    sd:"[Digivolve] from Lv.2 w/[Three Musketeers] in text: 0 cost",
    me:"[When Moving] [On Play] You may return 1 card with [Three Musketeers] in its text from your trash to your hand.",
    ie:"[Your Turn] [Once Per Turn] When cards are placed in this Digimon's digivolution cards, ＜Draw 1＞." },
  { n:"BB1-065", nm:"Sangloupmon", c:["Black","Purple"], t:"Digimon", s:"Champion", dt:["Dark Animal","CT"], a:"Virus", dp:5000, pc:5, lvl:4, evo:[{color:"Black",level:3,cost:3},{color:"Purple",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[CT] trait: 2 cost / [Garurumon] w/[CT] trait: 1 cost",
    me:"[On Play] [When Digivolving] Trash 1 card in your hand. Then, you may place 1 Level 4 or lower Digimon card with the [CT] trait from your trash as this Digimon's bottom digivolution card. Then, if this Digimon has 3 or more digivolution cards, you may digivolve into a Digimon in the trash with the [CT] trait with the cost reduced by 2.",
    ie:"[All Turns] While this Digimon has 3 or more digivolution cards, it gains ＜Reboot＞." },
  { n:"BB1-066", nm:"Minotarumon", c:["Black","Purple"], t:"Digimon", s:"Champion", dt:["Beastkin","ME"], a:"Virus", dp:5000, pc:5, lvl:4, evo:[{color:"Black",level:3,cost:3},{color:"Purple",level:3,cost:3}],
    sd:"[Digivolve] from Lv.3 w/[ME] trait: 2 cost",
    me:"＜Collision＞\n[On Play] [When Digivolving] By trashing 1 card with the [ME] trait from your hand, ＜De-Digivolve 1＞ 1 of your opponent's Digimon.",
    ie:"[When Attacking] [Once Per Turn] Reveal the top 3 cards of your deck. For each card with the [ME] trait, this Digimon gets +1000 DP until the end of your opponent's turn. Trash the rest." },
  { n:"BB1-067", nm:"Deputymon", c:["Black"], t:"Digimon", s:"Champion", dt:["Mutant","Three Musketeers"], a:"Vaccine", dp:6000, pc:6, lvl:4, evo:[{color:"Black",level:3,cost:2}],
    sd:"[Digivolve] from Lv.3 w/[Three Musketeers] in text: 2 cost", rule:"Treat this card as also having the [Three Musketeers] trait.",
    me:"[On Play] [When Digivolving] By placing 1 card with the [Three Musketeers] trait from your hand or trash as 1 of your Digimon's bottom digivolution cards, this Digimon's DP cannot be reduced by your opponent's effects until the end of their turn.",
    ie:"[Your Turn] [Once Per Turn] When cards are placed in this Digimon's digivolution cards, ＜Draw 1＞." },
  { n:"BB1-068", nm:"Cerberumon: Werewolf Mode", c:["Black","Purple"], t:"Digimon", s:"Ultimate", dt:["Wizard","CT"], a:"Virus", dp:7000, pc:7, lvl:5, evo:[{color:"Black",level:4,cost:4},{color:"Purple",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[CT] trait: 3 cost / [WereGarurumon] w/[CT] trait: 1 cost", asm:"[Assembly\u00a0-2] 2 Digimon cards with the [CT] trait",
    me:"[When Digivolving] You may place 1 card with the [CT] trait from your hand or trash under this Digimon as its bottom digivolution card. Then, if this Digimon has 5 or more digivolution cards ＜De-Digivolve 1＞ on 1 of your opponents Digimon.",
    ie:"[All Turns] While this Digimon has the [CT] trait, it gains ＜Scapegoat＞." },
  { n:"BB1-069", nm:"MetalGreymon", c:["Black"], t:"Digimon", s:"Ultimate", dt:["Cyborg"], a:"Virus", dp:7000, pc:7, lvl:5, evo:[{color:"Black",level:4,cost:3}],
    sd:"[Digivolve] from Lv.4 w/[Three Musketeers] in text: 3 cost", asm:"[Assembly\u00a0-2] 1 Option card with the [Three Musketeers] trait",
    me:"[On Play] [When Digivolving] By returning 3 cards with [Three Musketeers] in their texts from your deck to the top of your deck, gain 1 memory.\n[When Digivolving] [When Attacking] [Once Per Turn] By trashing 1 Option card from any of your Digimon's digivolution cards, delete 1 of your opponent's Digimon with a play cost of 5 or lower.",
    ie:"[All Turns] [Once Per Turn] When Option cards are trashed from this Digimon's digivolution cards, ＜De-Digivolve 1＞ 1 of your opponent's Digimon." },
  { n:"BB1-070", nm:"Rebellimon", c:["Black","Purple"], t:"Digimon", s:"Ultimate", dt:["Cyborg","ME"], a:"Virus", dp:7000, pc:7, lvl:5, evo:[{color:"Black",level:4,cost:4},{color:"Purple",level:4,cost:4}],
    sd:"[Digivolve] from Lv.4 w/[ME] trait: 3 cost", dna:"[DNA Digivolve] [Black]/[Red] Lv.4 + [Purple]/[Yellow] Lv.4\u00a0: Cost 0",
    me:"＜Collision＞ ＜Piercing＞\n[On Play] [When Digivolving] Reveal the top 3 cards of your deck. Then, delete 1 of your opponent's play cost 5 or lower Digimon. For each card with the [ME] trait revealed, add 1 to the maximum play cost this effect can delete. Trash the revealed cards.\n[All Turns] [Once Per Turn] When any of your cards with the [ME] trait are trashed from your revealed cards, 1 of your other Level 5 or lower Digimon with the [ME] trait may digivolve into 1 of the trashed cards without paying its digivolution cost.",
    ie:"[All Turns] [Once Per Turn] When cards are trashed from this Digimon's digivolution cards or your revealed cards, ＜De-Digivolve 1＞ 1 of your opponent's Digimon." },
  { n:"BB1-071", nm:"Gundramon", c:["Black"], t:"Digimon", s:"Mega", dt:["Machine"], a:"Virus", dp:13000, pc:13, lvl:6, evo:[{color:"Black",level:5,cost:4}],
    sd:"[Digivolve] from Lv.5 w/[Three Musketeers] in text: 4 cost",
    me:"＜Reboot＞ ＜Blocker＞\n[When Digivolving] [When Attacking] [Once Per Turn] Reveal the top 6 cards of your deck. You may use 1 card with the [Three Musketeers] trait from among them without paying the cost. Return the rest to the bottom of the deck.\n[All Turns] When any of your Digimon with the [Three Musketeers] trait would leave the battle area, by trashing 1 Option card from this Digimon's digivolution cards, they do not leave." },
  { n:"BB1-072", nm:"Plutomon", c:["Black","Purple"], t:"Digimon", s:"Mega", dt:["Shaman","CT"], a:"Virus", dp:12000, pc:12, lvl:6, evo:[{color:"Black",level:5,cost:4},{color:"Purple",level:5,cost:4}],
    sd:"[Digivolve] from Lv.5 w/[CT] trait: 4 cost",
    me:"＜Collision＞\n[When Digivolving] [When Attacking] [Once Per Turn] By placing 2 Digimon cards with the [CT] trait from your trash as this Digimon's bottom digivolution cards, delete 1 of your opponent's Level 4 or lower Digimon. For every 3 cards in this Digimon's digivolution cards, add 1 to the maximum level this effect can choose.\n[All Turns] [Once Per Turn] When cards with the [CT] trait are added to this Digimon's digivolution cards, ＜De-Digivolve 1＞ 1 of your opponent's Digimon." },
  { n:"BB1-073", nm:"Omnimon Zwart Defeat", c:["Black","Purple","White"], t:"Digimon", s:"Mega", dt:["Holy Warrior","CT"], a:"Virus", dp:15000, pc:15, lvl:7, evo:[{color:"Black",level:6,cost:6},{color:"Purple",level:6,cost:6}],
    sd:"[Digivolve] from Lv.6 w/[CT] trait: 5 cost",
    me:"＜Execute＞\n[When Digivolving] ＜De-Digivolve 1＞ all of your opponent's Digimon.\n[When Attacking] [Once Per Turn] Delete 1 of your opponent's Digimon with a play cost of 5 or lower. For every 3 cards in this Digimon's digivolution cards, you may delete 1 additional of your opponent's Digimon with a play cost of 5 or lower.\n[On Deletion] You may play 1 Level 5 or lower Digimon card with the [CT] trait from your trash without paying the cost." },
  
  { n:"BB1-074", nm:"Ghostmon", c:["Purple"], t:"Digimon", s:"Rookie", dt:["Ghost","CT"], a:"Data", dp:2000, pc:3, lvl:3, evo:[{color:"Purple",level:2,cost:0}],
    sd:"[Digivolve] from Lv.2 w/[CT] trait: 0 cost",
    me:"[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon or Option card with the [CT] trait and 1 [Ridendo Fusco] from among them to your hand. Return the rest to the bottom of the deck.",
    ie:"[Your Turn] [Once Per Turn] When you use an Option card with the [CT] trait, ＜Draw 1＞." },
  { n:"BB1-075", nm:"Mochi", c:["Purple","Green"], t:"Digimon", s:"Rookie", dt:["Beast","Re;Ware","Girlies"], a:"Vaccine", dp:2000, pc:3, lvl:3, evo:[{color:"Purple",level:2,cost:0},{color:"Green",level:2,cost:0}],
    sd:"[Digivolve] from Lv.2 w/[Re;Ware] or [Girlies] trait: 0 cost",
    me:"[Main] By suspending 1 Digimon or Tamer with the [Re;Ware] or [Girlies] trait, or if you have [Hina Kurafutā], this Digimon may digivolve into a Digimon card with the [Re;Ware] or [Girlies] trait with its digivolution cost reduced by 2.",
    ie:"＜Reboot＞" },
  { n:"BB1-076", nm:"Seasarmon", c:["Purple","Green"], t:"Digimon", s:"Champion", dt:["Holy Beast","Re;Ware","Girlies"], a:"Vaccine", dp:6000, pc:5, lvl:4, evo:[{color:"Purple",level:3,cost:2},{color:"Green",level:3,cost:2}],
    sd:"[Digivolve] from Lv.3 w/[Re;Ware] or [Girlies] trait: 2 cost",
    me:"[When Moving] [When Digivolving] If a Digimon card with the [Re;Ware] or [Girlies] trait is in this Digimon's digivolution cards, you may play 1 Tamer card with the [Re;Ware] or [Girlies] trait from your hand without paying the cost. Then, you may place 1 card with the [Re;Ware] or [Girlies] trait from your hand or trash as this Digimon's bottom digivolution card.",
    ie:"[Main] [Once Per Turn] By suspending 1 Digimon or Tamer with the [Re;Ware] or [Girlies] trait, gain 1 memory." },
  { n:"BB1-077", nm:"Bakemon", c:["Purple"], t:"Digimon", s:"Champion", dt:["Ghost","CT"], a:"Virus", dp:4000, pc:4, lvl:4, evo:[{color:"Purple",level:3,cost:2}],
    sd:"[Digivolve] from Lv.3 w/[CT] trait: 2 cost",
    me:"[Main] [Once Per Turn] You may play or use 1 card with the [CT] trait from your hand with the cost reduced by 2.\n[Your Turn] [Once Per Turn] When you use an Option card with the [CT] trait, ＜Draw 1＞." },
  { n:"BB1-078", nm:"Velgrmon", c:["Purple","Red"], t:"Digimon", s:"Champion", dt:["Giant Bird","Girlies"], a:"Virus", dp:6000, pc:6, lvl:4, evo:[{color:"Purple",level:3,cost:4},{color:"Red",level:3,cost:4}],
    sd:"[Digivolve] from Lv.3 w/[Girlies] trait: 3 cost / [GulusGammamon] w/[Girlies] trait: 1 cost",
    me:"[On Play] [When Digivolving] Your opponent plays 1 Level 4 or lower Digimon card from your trash suspended without paying the cost. [On Play] effects of Digimon played by this effect do not activate.\n[Your Turn] When an opponent's Digimon is played, this Digimon may digivolve into a Digimon card with the [Girlies] trait in your trash with its digivolution cost reduced by 1.",
    ie:"[Your Turn] This Digimon gets +2000 DP." },
  { n:"BB1-079", nm:"Caturamon", c:["Purple","Green"], t:"Digimon", s:"Ultimate", dt:["Holy Beast","Re;Ware","Girlies"], a:"Vaccine", dp:8000, pc:8, lvl:5, evo:[{color:"Purple",level:4,cost:3},{color:"Green",level:4,cost:3}],
    sd:"[Digivolve] from Lv.4 w/[Re;Ware] or [Girlies] trait: 3 cost",
    me:"＜Fortitude＞ ＜Decode («Lv.4 w/[Re;Ware] or [Girlies] trait»)＞\n[When Digivolving] You may hatch in your breeding area. Then, 1 of your Digimon with the [Re;Ware] or [Girlies] trait in the breeding area may digivolve into a Level 5 or lower Digimon card with the [Re;Ware] or [Girlies] trait in your hand without paying its digivolution cost.",
    ie:"＜Alliance＞" },
  { n:"BB1-080", nm:"Phantomon", c:["Purple"], t:"Digimon", s:"Ultimate", dt:["Ghost","CT"], a:"Virus", dp:7000, pc:7, lvl:5, evo:[{color:"Purple",level:4,cost:3}],
    sd:"[Digivolve] from Lv.4 w/[CT] trait: 3 cost",
    me:"＜Scapegoat＞\n[When Attacking] By placing 1 of your [Ridendo Fusco] as this Digimon's bottom digivolution card, this Digimon may digivolve into a Digimon card with the [CT] trait in the hand with its digivolution cost reduced by 2.",
    ie:"[End of Attack] [Once Per Turn] By unsuspending this Digimon, delete 1 of your lowest level Digimon." },
  { n:"BB1-081", nm:"Dalphomon", c:["Purple","Green"], t:"Digimon", s:"Mega", dt:["Beast","Re;Ware","Girlies"], a:"Vaccine", dp:11000, pc:12, lvl:6, evo:[{color:"Purple",level:5,cost:4},{color:"Green",level:5,cost:4}],
    sd:"[Digivolve] from Lv.5 w/[Re;Ware] or [Girlies] trait: 3 cost",
    me:"＜Alliance＞ ＜Blocker＞\n[When Digivolving] [On Deletion] 1 of your other Digimon may digivolve into a Level 6 or lower Digimon card with the [Re;Ware] or [Girlies] trait in your hand or trash without paying its digivolution cost.\n[When Attacking] [Once Per Turn] By suspending 1 Digimon or Tamer with the [Re;Ware] or [Girlies] trait, this Digimon unsuspends.",
    ie:"[When Attacking] [Once Per Turn] By suspending 1 Digimon or Tamer with the [Re;Ware] or [Girlies] trait, this Digimon unsuspends." },
  { n:"BB1-082", nm:"Piedmon", c:["Purple","Yellow"], t:"Digimon", s:"Mega", dt:["Wizard","CT"], a:"Virus", dp:12000, pc:12, lvl:6, evo:[{color:"Purple",level:5,cost:4},{color:"Yellow",level:5,cost:4}],
    sd:"[Digivolve] from Lv.5 w/[CT] trait: 4 cost",
    me:"＜Alliance＞ ＜Partition {[Ridendo Fusco] & [Phantomon]}＞\n[When Digivolving] [When Attacking] 1 of your opponent's Digimon gets -6000 DP for the turn. Then, if you have a [Ridendo Fusco] you may use an option card from your hand or trash with the cost reduced by 2.\n[All Turns] [Once Per Turn] When Digimon are deleted, you may play 1 [Stage Hand] Token *(Digimon/Lv.4/Purple/4000 DP/＜Guard＞)*.\n[All Turns] When this Digimon's DP is reduced by an opponent's effect, you may trash 1 Digimon card with the [CT] trait in your hand to apply that effect to 1 of both players' Digimon with a level less than or equal to the trashed card's level." },
  { n:"BB1-083", nm:"Boltboutamon/Curtain Call", c:["Purple","Yellow","Black"], t:"Digimon/Option", s:"Mega", dt:["Wizard","CT"], a:"Virus", dp:15000, pc:15, lvl:7, evo:[{color:"Purple",level:6,cost:5},{color:"Yellow",level:6,cost:5},{color:"Black",level:6,cost:5}],
    sd:"[Digivolve] from Lv.6 w/[CT] trait: 5 cost",
    me:"＜Alliance＞ ＜Partition {[Ridendo Fusco] & [Phantomon]}＞\n[When Digivolving] For each of this Digimon's digivolution cards, 1 of your opponent's Digimon gets -2000 DP for the turn. Then, you may use 1 Option card with the [CT] trait from your hand or trash without paying the cost.\n[All Turns] [Once Per Turn] When non-Token Digimon are deleted, you may activate 1 [Main] effect on this card's Option side.",
    ocolor:"Purple",
    oef:"＜Use Req. ([CT] trait)＞\n[Main] Play 1 [Stage Hand] Token. Then, delete 1 of your opponent's Level 5 or lower Digimon. For each of your [Stage Hand]s, increase the maximum level this effect can choose by 1." },

  { n:"BB1-084", nm:"Nathan James", c:["Red","Blue","White"], t:"Tamer", dt:["Nerds","IADA"], pc:4,
    me:"[Start of Your Main Phase] If you have a Digimon with the [Nerds] trait, gain 1 memory.\n[End of Your Turn] By suspending this Tamer, ＜Draw 1＞. Then, 1 of your Level 5 or higher Digimon with the [Nerds] or [IADA] trait may attack.",
    se:"[Security] Play this card without paying the cost." },
  { n:"BB1-085", nm:"Director Watanabe", c:["Blue","Black"], t:"Tamer", dt:["IADA"], pc:5,
    me:"[Start of Your Turn] If your memory is 2 or less, set it to 3.\n[On Play] Reveal the top 3 cards of your deck. Add 1 card with the [IADA] trait from among them to your hand. Return the rest to the bottom of the deck.\n[All Turns] When any of your other Tamers with the [IADA] trait are played, by suspending this Tamer, gain 1 memory.",
    se:"[Security] Play this card without paying the cost." },
  { n:"BB1-086", nm:"Laura Loath", c:["Blue"], t:"Tamer", dt:[], pc:4,
    me:"[Start of Your Turn] If your memory is 2 or less, set it to 3.\n[Your Turn] When 1 of your [Blue] Digimon with [Greymon] in its name becomes suspended, by suspending this Tamer, you may use 1 [Blue] Option card with [Greymon] in its text without paying the cost.",
    se:"[Security] Play this card without paying the cost." },
  { n:"BB1-086_P1", mn:"BB1-086", nm:"Laura Loath", c:["Blue"], t:"Tamer", dt:[], pc:4,
    me:"[Start of Your Turn] If your memory is 2 or less, set it to 3.\n[Your Turn] When 1 of your [Blue] Digimon with [Greymon] in its name becomes suspended, by suspending this Tamer, you may use 1 [Blue] Option card with [Greymon] in its text without paying the cost.",
    se:"[Security] Play this card without paying the cost." },
  { n:"BB1-087", nm:"Cassidy Ibushi", c:["Yellow","Black"], t:"Tamer", dt:["DC"], pc:4,
    me:"[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory.\n[All Turns] When this Tamer becomes suspended, for the turn, 1 of your Digimon gets +3000 DP and 1 of your opponent's Digimon gets -3000 DP. Then, 1 of your Digimon with the [DC] trait cannot be deleted by battle or have its digivolution cards trashed until the end of your opponent's turn.",
    se:"[Security] Play this card without paying the cost." },
  { n:"BB1-088", nm:"Dane Cathal", c:["Yellow"], t:"Tamer", dt:["IADA"], pc:3,
    me:"[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory.\n[Your Turn] When any of your Digimon with the [IADA] trait become suspended, by suspending this Tamer, 2 of your Digimon gain ＜Barrier＞ until the end of your opponent's turn.",
    se:"[Security] Play this card without paying the cost." },
  { n:"BB1-089", nm:"Leon Wilson", c:["Green","Purple"], t:"Tamer", dt:["Arena","Nerds"], pc:5,
    me:"[Start of Your Turn] If your memory is 2 or less, set it to 3.\n[Your Turn] When 1 of your Digimon with the [Nerds] or [Arena] trait attacks, by suspending this Tamer, ＜Draw 1＞, then trash 1 card in your hand. Then, if attacking 1 of your opponent's Digimon, 1 of your Digimon may digivolve into a Digimon card with the [Arena] or [Nerds] trait in your trash with its digivolution cost reduced by 1.",
    se:"[Security] Play this card without paying the cost." },
  { n:"BB1-090", nm:"Oryon Sonier", c:["Green","Yellow"], t:"Tamer", dt:["Nerds","IADA"], pc:4,
    me:"[Start of Your Main Phase] If you have a Digimon with the [Nerds] or [IADA] trait, gain 1 memory.\n[Your Turn] When any of your Digimon with the [Nerds] or [IADA] trait are played or digivolve, by suspending this Tamer, 1 of your Level 5 or higher Digimon with the [Nerds] or [IADA] trait gains ＜Alliance＞ for the turn.",
    se:"[Security] Play this card without paying the cost." },
  { n:"BB1-091", nm:"Taiyo James", c:["Black","Blue"], t:"Tamer", dt:["CT"], pc:5,
    me:"[Start of Your Turn] If your memory is 2 or less, set it to 3.\n[On Play] By trashing 1 card with the [CT] trait from your hand, ＜Draw 2＞.\n[Your Turn] When 1 of your Digimon cards with the [CT] trait would be played, by suspending this Tamer, reduce the cost by 2.",
    se:"[Security] Play this card without paying the cost." },
  { n:"BB1-092", nm:"Hina Kurafutā & Ikuyo Korotatsu", c:["Purple","Red"], t:"Tamer", dt:["Re;Ware","Girlies"], pc:4,
    me:"[Start of Your Main Phase] By trashing 1 card from your hand, ＜Draw 1＞ and gain 1 memory.\n[Your Turn] When 1 of your Digimon with the [Re;Ware], [Girlies], [Dark Dragon], or [Evil Dragon] trait digivolves from the trash, by suspending this Tamer, that Digimon gains ＜Piercing＞ for the turn. Then, that Digimon may attack.",
    se:"[Security] Play this card without paying the cost." },
  { n:"BB1-093", nm:"Ridendo Fusco", c:["Purple"], t:"Tamer", dt:["CT"], pc:3,
    me:"[Start of Your Main Phase] If you have an Option card with the [CT] trait in the battle area or face-up in your security, gain 1 memory.\n[Your Turn] When an Option card with the [CT] trait would be used, by suspending this Tamer, reduce the cost by 2.",
    se:"[Security] Play this card without paying the cost." },

  { n:"BB1-094", nm:"Nerds Assemble", c:["Red","Green","Yellow"], t:"Option", dt:["Nerds"], pc:3,
    me:"＜Use Req. ([Nerds] trait)＞\n[Main] Reveal the top 3 cards of your deck. Add 1 card with the [Nerds] trait from among them to your hand. Return the rest to the bottom of the deck.\n[Main] ＜Delay＞\n· Gain 2 memory.",
    se:"[Security] Place this card in the battle area." },
  { n:"BB1-095", nm:"Chaotic Thunder Tuning", c:["Blue"], t:"Option", dt:[], pc:3,
    me:"[Main] If you have [Laura Loath] or in the digivolution cards of any of your Digimon, you may unsuspend 1 of your Digimon with [ShineGreymon] in its name, then place this card in the battle area.\n[All Turns] When 1 of your [Blue] Digimon with [Greymon] in its name would be deleted, ＜Delay＞.\n· You may play 1 Level 4 or lower [Blue] Digimon card and 1 [Laura Loath] from that Digimon's digivolution cards without paying the cost.",
    se:"[Security] Suspend 1 of your opponent's Digimon, then add this card to your hand." },
  { n:"BB1-096", nm:"Driver City", c:["Yellow","Green"], t:"Option", dt:["DC"], pc:3,
    me:"＜Use Req. ([DC] trait)＞\n[Security] All of your Digimon with the [DC] trait gain ＜Piercing＞. All of your Tamers with the [DC] trait gain ＜Rush＞.\n[Main] Add your bottom security card to your hand and place this card face-up as your bottom security card. Then, you may play 1 card with the [DC] trait from your hand with its play cost reduced by 3.",
    se:"[Security] You may play 1 play cost 5 or lower card with the [DC] trait from your hand or trash without paying the cost." },
  { n:"BB1-097", nm:"World Digimon Wrestling Championship Belt", c:["Green","Black"], t:"Option", dt:["Arena"], pc:3,
    me:"＜Use Req. ([Arena] trait)＞\n[Main] Unsuspend 1 of your Digimon. Then, you may link this card to 1 of your Digimon without paying the cost.",
    lDP:3000, lEf:"[All Turns] [Once Per Turn] When this Digimon wins a battle, trash your opponent's top security card.", lReq:"[Link] [Arena] trait: 2 cost",
    se:"[Security] Suspend 1 of your opponent's Digimon. Then, add this card to your hand." },
  { n:"BB1-098", nm:"Deep Network", c:["Black","Purple"], t:"Option", dt:["CT"], pc:5,
    me:"＜Use Req. ([CT] trait)＞\n[Security] [All Turns] [Once Per Turn] When 1 of your Level 6 or higher Digimon with the [CT] trait would be deleted, you may play 1 Level 5 or lower Digimon card with the [CT] trait from that Digimon's digivolution cards without paying the cost.\n[Main] Add your bottom security card to your hand and place this card face-up as your bottom security card. Then, you may play 1 Digimon card with the [CT] trait from your hand with its play cost reduced by 3.",
    se:"[Security] You may play 1 Level 4 or lower Digimon card with the [CT] trait from your hand or trash without paying the cost." },
  { n:"BB1-099", nm:"Hell Training", c:["Purple"], t:"Option", dt:["Girlies"], pc:2,
    me:"＜Use Req. ([Girlies] trait)＞\n[Main] Reveal the top 2 cards of your deck. You may trash 1 card with the [Girlies] trait from among them. Return the rest to the bottom of the deck.\n[Main] ＜Delay＞\n· 1 of your Digimon may digivolve into a Digimon card with the [Girlies] trait in your trash with its digivolution cost reduced by 2.",
    se:"[Security] You may trash 1 card in your hand. Then, place this card in the battle area." },
  { n:"BB1-100", nm:"Puppetmaster", c:["Purple","Black"], t:"Option", dt:["CT"], pc:4,
    me:"＜Use Req. ([CT] trait)＞\n[Main] By trashing 1 card with the [CT] trait in your hand, place this card in the battle area.\n[Opponent's Turn] When an opponent's Digimon attacks while you have a level 5 or higher [CT] trait Digimon, ＜Delay＞.\n· The attacking Digimon battles 1 of your opponent's other Digimon. Then, end the attack.",
    se:"[Security] Add this card to your hand." },
  { n:"BB1-101", nm:"The Fool", c:["Purple","Yellow"], t:"Option", dt:["CT"], pc:3,
    me:"＜Use Req. ([CT] trait)＞\n[Main] You may play 1 level 3 or lower Digimon with the [CT] trait or 1 [Ridendo Fusco] from your hand or trash without paying the cost. Then, place this card in the battle area.\n[All Turns] When 1 of your Digimon with the [CT] trait would leave the battle area, ＜Delay＞.\n· You may play 1 [Fool] Token and change its original DP and colors to the original DP and colors of that Digimon. *(Digimon/Purple/3000 DP/＜Blocker＞ ＜Retaliation＞)*",
    se:"[Security] Add this card to your hand." },
  { n:"BB1-102", nm:"Resolution No. 256 of the 65th United Nations...", c:["White"], t:"Option", dt:["IADA"], pc:3,
    me:"＜Use Req. ([IADA] trait)＞\n[Main] You may play 1 Tamer card or Level 3 Digimon card with the [IADA] trait from your hand or trash without paying the cost. Then, place this card in the battle area.\n[Your Turn] When any of your Tamers with the [IADA] trait become suspended, ＜Delay＞.\n· 1 of your Digimon with the [IADA] trait may digivolve into a Digimon card with the [IADA] trait with its digivolution cost reduced by 1. For each of your Tamers with the [IADA] trait and different names, further reduce the cost by 1.",
    se:"[Security] Activate this card's [Main] effects." }
];

const mappedCards = bb1Cards.map(c => ({
  uniqueCardNumber: c.n,
  cardNumber: c.mn || c.n,
  name: c.nm,
  imgUrl: cdn + c.n + ".webp",
  cardType: c.t,
  color: c.c,
  stage: c.s || null,
  digiType: c.dt,
  attribute: c.a || null,
  dp: c.dp || null,
  playCost: c.pc,
  level: c.lvl || null,
  mainEffect: c.me || null,
  inheritedEffect: c.ie || null,
  securityEffect: c.se || null,
  digivolveConditions: c.evo || [],
  specialDigivolve: c.sd || null,
  dnaDigivolve: c.dna || null,
  assembly: c.asm || null,
  digiXros: c.xros || null,
  rule: c.rule || null,
  dualEffect: c.de || null,
  optionCardColorRequirement: c.ocolor || null,
  optionCardEffect: c.oef || null,
  linkDP: c.lDP || null,
  linkEffect: c.lEf || null,
  linkRequirement: c.lReq || null,
  restrictions: { chinese: "Unrestricted", english: "Unrestricted", japanese: "Unrestricted", korean: "Unrestricted" },
  illustrator: "Beyond The Bonds",
  _class: "com.github.wekaito.backend.models.Card"
}));

db.card.insertMany(mappedCards);
print(`Successfully imported ${mappedCards.length} BB1 cards!`);
