// ==========================================
// MASTER IMPORT SCRIPT FOR BB1, ST01 & SC1
// ==========================================

const cdnBase = "https://raw.githubusercontent.com/NJTAHJ/Bonds-Beyond-Custom-Client/main/frontend/public/";

// 1. Clean up existing custom card entries
db.card.deleteMany({ uniqueCardNumber: { $regex: "^(BB1|ST01|SC1)" } });

// 2. Re-insert all custom cards
db.card.insertMany([
  // --- LEVEL 7 MEGAS / SPECIAL MECHANICS ---
  {
    "uniqueCardNumber": "BB1-104",
    "name": "Omnimon",
    "imgUrl": cdnBase + "BB1-104.webp",
    "cardType": "Digimon",
    "color": ["White", "Blue", "Red"],
    "attribute": "Vaccine",
    "cardNumber": "BB1-104",
    "digivolveConditions": [],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nerds] trait: 5 cost",
    "dnaDigivolve": "[DNA Digivolve] [Red]/[Yellow] Lv.6 + [Blue]/[Green] Lv.6\u00a0: Cost 0",
    "stage": "Mega",
    "digiType": ["Holy Knight", "Nerds", "IADA"],
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "＜Partition {[WarGreymon] & [MetalGarurumon]}＞\n[When Digivolving] [When Attacking] [Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand or trash without paying the cost. If DNA digivolving, add 1 to the number of cards this effect can play.\n[All Turns] [Once Per Turn] When Digimon with the [Nerds] trait are played, 1 of your opponent's Digimon gets -5000 DP for each of your Digimon with the [Nerds] trait until the end of their turn.\n[All Turns] [Once Per Turn] When a Digimon is deleted, unsuspend this Digimon.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-104_P1",
    "name": "Omnimon",
    "imgUrl": cdnBase + "BB1-104_P1.webp",
    "cardType": "Digimon",
    "color": ["White", "Blue", "Red"],
    "attribute": "Vaccine",
    "cardNumber": "BB1-104",
    "digivolveConditions": [],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nerds] trait: 5 cost",
    "dnaDigivolve": "[DNA Digivolve] [Red]/[Yellow] Lv.6 + [Blue]/[Green] Lv.6\u00a0: Cost 0",
    "stage": "Mega",
    "digiType": ["Holy Knight", "Nerds", "IADA"],
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "＜Partition {[WarGreymon] & [MetalGarurumon]}＞\n[When Digivolving] [When Attacking] [Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand or trash without paying the cost. If DNA digivolving, add 1 to the number of cards this effect can play.\n[All Turns] [Once Per Turn] When Digimon with the [Nerds] trait are played, 1 of your opponent's Digimon gets -5000 DP for each of your Digimon with the [Nerds] trait until the end of their turn.\n[All Turns] [Once Per Turn] When a Digimon is deleted, unsuspend this Digimon.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-104_P2",
    "name": "Omnimon",
    "imgUrl": cdnBase + "BB1-104_P2.webp",
    "cardType": "Digimon",
    "color": ["White", "Blue", "Red"],
    "attribute": "Vaccine",
    "cardNumber": "BB1-104",
    "digivolveConditions": [],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nerds] trait: 5 cost",
    "dnaDigivolve": "[DNA Digivolve] [Red]/[Yellow] Lv.6 + [Blue]/[Green] Lv.6\u00a0: Cost 0",
    "stage": "Mega",
    "digiType": ["Holy Knight", "Nerds", "IADA"],
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "＜Partition {[WarGreymon] & [MetalGarurumon]}＞\n[When Digivolving] [When Attacking] [Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand or trash without paying the cost. If DNA digivolving, add 1 to the number of cards this effect can play.\n[All Turns] [Once Per Turn] When Digimon with the [Nerds] trait are played, 1 of your opponent's Digimon gets -5000 DP for each of your Digimon with the [Nerds] trait until the end of their turn.\n[All Turns] [Once Per Turn] When a Digimon is deleted, unsuspend this Digimon.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-103",
    "name": "TyrantKabuterimon",
    "imgUrl": cdnBase + "BB1-103.webp",
    "cardType": "Digimon",
    "color": ["Green"],
    "cardNumber": "BB1-103",
    "digivolveConditions": [{ "color": "Green", "level": 6, "cost": 6 }],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Insectoid] trait with 13000 DP or less: 3 cost",
    "stage": "Mega",
    "digiType": ["Insectoid", "Nerds", "Arena"],
    "attribute": "Virus",
    "dp": 14000,
    "playCost": 14,
    "level": 7,
    "mainEffect": "＜Vortex＞ ＜Piercing＞\n[When Digivolving] Play 1 [Drone] Token (Green/Digimon/Insectoid/2000 DP/this Digimon cannot unsuspend. On Deletion: Suspend 1 of your opponent's Digimon) to your opponent's field suspended. Then, play up to 5 play cost of Digimon cards with the [Nerds], [Arena], or [Insectoid] traits from your trash without paying their memory costs. For each of your opponent's suspended Digimon, increase the total play cost you can play by 2.\n[All Turns] All of your other Digimon with the [Insectoid], [Arena], or [Nerds] trait gain ＜Retaliate＞.\n[All Turns] [Once Per Turn] When a Digimon is played, 1 of your other Digimon may battle 1 of your opponent's Digimon.",
    "rule": "This card is also treated as having the [Free] trait.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-103_P1",
    "name": "TyrantKabuterimon",
    "imgUrl": cdnBase + "BB1-103_P1.webp",
    "cardType": "Digimon",
    "color": ["Green"],
    "cardNumber": "BB1-103",
    "digivolveConditions": [{ "color": "Green", "level": 6, "cost": 6 }],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Insectoid] trait with 13000 DP or less: 3 cost",
    "stage": "Mega",
    "digiType": ["Insectoid", "Nerds", "Arena"],
    "attribute": "Virus",
    "dp": 14000,
    "playCost": 14,
    "level": 7,
    "mainEffect": "＜Vortex＞ ＜Piercing＞\n[When Digivolving] Play 1 [Drone] Token (Green/Digimon/Insectoid/2000 DP/this Digimon cannot unsuspend. On Deletion: Suspend 1 of your opponent's Digimon) to your opponent's field suspended. Then, play up to 5 play cost of Digimon cards with the [Nerds], [Arena], or [Insectoid] traits from your trash without paying their memory costs. For each of your opponent's suspended Digimon, increase the total play cost you can play by 2.\n[All Turns] All of your other Digimon with the [Insectoid], [Arena], or [Nerds] trait gain ＜Retaliate＞.\n[All Turns] [Once Per Turn] When a Digimon is played, 1 of your other Digimon may battle 1 of your opponent's Digimon.",
    "rule": "This card is also treated as having the [Free] trait.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-103_P2",
    "name": "TyrantKabuterimon",
    "imgUrl": cdnBase + "BB1-103_P2.webp",
    "cardType": "Digimon",
    "color": ["Green"],
    "cardNumber": "BB1-103",
    "digivolveConditions": [{ "color": "Green", "level": 6, "cost": 6 }],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Insectoid] trait with 13000 DP or less: 3 cost",
    "stage": "Mega",
    "digiType": ["Insectoid", "Nerds", "Arena"],
    "attribute": "Virus",
    "dp": 14000,
    "playCost": 14,
    "level": 7,
    "mainEffect": "＜Vortex＞ ＜Piercing＞\n[When Digivolving] Play 1 [Drone] Token (Green/Digimon/Insectoid/2000 DP/this Digimon cannot unsuspend. On Deletion: Suspend 1 of your opponent's Digimon) to your opponent's field suspended. Then, play up to 5 play cost of Digimon cards with the [Nerds], [Arena], or [Insectoid] traits from your trash without paying their memory costs. For each of your opponent's suspended Digimon, increase the total play cost you can play by 2.\n[All Turns] All of your other Digimon with the [Insectoid], [Arena], or [Nerds] trait gain ＜Retaliate＞.\n[All Turns] [Once Per Turn] When a Digimon is played, 1 of your other Digimon may battle 1 of your opponent's Digimon.",
    "rule": "This card is also treated as having the [Free] trait.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-083",
    "name": "Boltboutamon/Curtain Call",
    "imgUrl": cdnBase + "BB1-083.webp",
    "cardType": "Digimon/Option",
    "color": ["Purple", "Yellow", "Black"],
    "cardNumber": "BB1-083",
    "digivolveConditions": [
      { "color": "Purple", "level": 6, "cost": 5 },
      { "color": "Yellow", "level": 6, "cost": 5 },
      { "color": "Black", "level": 6, "cost": 5 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[CT] trait: 5 cost",
    "stage": "Mega",
    "digiType": ["Wizard", "CT"],
    "attribute": "Virus",
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "＜Alliance＞ ＜Partition {[Ridendo Fusco] & [Phantomon]}＞\n[When Digivolving] For each of this Digimon's digivolution cards, 1 of your opponent's Digimon gets -2000 DP for the turn. Then, you may use 1 Option card with the [CT] trait from your hand or trash without paying the cost.\n[All Turns] [Once Per Turn] When non-Token Digimon are deleted, you may activate 1 [Main] effect on this card's Option side.",
    "dualEffect": "[Arts Digivolve]",
    "optionCardColorRequirement": "Purple",
    "optionCardEffect": "＜Use Req. ([CT] trait)＞\n[Main] Play 1 [Stage Hand] Token. Then, delete 1 of your opponent's Level 5 or lower Digimon. For each of your [Stage Hand]s, increase the maximum level this effect can choose by 1.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- TAMERS ---
  {
    "uniqueCardNumber": "BB1-084",
    "name": "Nathan James",
    "imgUrl": cdnBase + "BB1-084.webp",
    "cardType": "Tamer",
    "color": ["Red", "Blue", "White"],
    "cardNumber": "BB1-084",
    "digiType": ["Nerds", "IADA"],
    "playCost": 4,
    "mainEffect": "[Start of Your Turn] If you have a Digimon with the [Nerds] or [IADA] trait in play, gain 1 memory.\n[End of Your Turn] [Once Per Turn] By suspending this Tamer, ＜Draw 1＞. Then, 1 of your Level 5 or higher Digimon with the [Nerds] or [IADA] trait may attack.",
    "securityEffect": "[Security] Play this card without paying its memory cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-086",
    "name": "Laura Loath",
    "imgUrl": cdnBase + "BB1-086.webp",
    "cardType": "Tamer",
    "color": ["Blue"],
    "cardNumber": "BB1-086",
    "digiType": [],
    "playCost": 4,
    "mainEffect": "[Start of Your Turn] If you have 2 or less memory, set it to 3.\n[Your Turn] When one of your Blue Digimon with [Greymon] in its name suspends, by suspending this Tamer, you may use 1 Blue Option card with [Greymon] in its text without paying the cost.",
    "securityEffect": "[Security] Play this card without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-086_P1",
    "name": "Laura Loath",
    "imgUrl": cdnBase + "BB1-086_P1.webp",
    "cardType": "Tamer",
    "color": ["Blue"],
    "cardNumber": "BB1-086",
    "digiType": [],
    "playCost": 4,
    "mainEffect": "[Start of Your Turn] If you have 2 or less memory, set it to 3.\n[Your Turn] When one of your Blue Digimon with [Greymon] in its name suspends, by suspending this Tamer, you may use 1 Blue Option card with [Greymon] in its text without paying the cost.",
    "securityEffect": "[Security] Play this card without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-085",
    "name": "Anubismon",
    "imgUrl": cdnBase + "BB1-085.webp",
    "cardType": "Digimon",
    "color": ["Purple"],
    "cardNumber": "BB1-085",
    "digivolveConditions": [{ "color": "Purple", "level": 5, "cost": 3 }],
    "stage": "Mega",
    "digiType": ["Shaman"],
    "attribute": "Vaccine",
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "[When Digivolving] You may play 1 Level 4 or lower Digimon card from your trash without paying its memory cost.\n[All Turns] All of your Digimon played from the trash gain ＜Rush＞ for the turn.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-085_P1",
    "name": "Anubismon",
    "imgUrl": cdnBase + "BB1-085_P1.webp",
    "cardType": "Digimon",
    "color": ["Purple"],
    "cardNumber": "BB1-085",
    "digivolveConditions": [{ "color": "Purple", "level": 5, "cost": 3 }],
    "stage": "Mega",
    "digiType": ["Shaman"],
    "attribute": "Vaccine",
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "[When Digivolving] You may play 1 Level 4 or lower Digimon card from your trash without paying its memory cost.\n[All Turns] All of your Digimon played from the trash gain ＜Rush＞ for the turn.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-087",
    "name": "Cassidy Ibushi",
    "imgUrl": cdnBase + "BB1-087.webp",
    "cardType": "Tamer",
    "color": ["Yellow"],
    "cardNumber": "BB1-087",
    "digiType": ["DC"],
    "playCost": 4,
    "mainEffect": "[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory.\n[All Turns] When this Tamer becomes suspended, for the turn, 1 of your Digimon gets +3000 DP and 1 of your opponent's Digimon gets -3000 DP. Then, 1 of your Digimon with the [DC] trait cannot be deleted by battle or have its digivolution cards trashed until the end of your opponent's turn.",
    "securityEffect": "[Security] Play this card without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- DIGI-EGGS & ROOKIES ---
  {
    "uniqueCardNumber": "BB1-001",
    "name": "Koromon",
    "imgUrl": cdnBase + "BB1-001.webp",
    "cardType": "Digi-Egg",
    "color": ["Red"],
    "cardNumber": "BB1-001",
    "stage": "In-Training",
    "digiType": ["Lesser", "Nerds"],
    "level": 2,
    "inheritedEffect": "[Your Turn] [Once Per Turn] When one of your other Digimon with the [Nerds] trait is played, this Digimon may digivolve into a Digimon card in your hand with the [Nerds] trait with its digivolution cost reduced by 1.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-005",
    "name": "Dorimon",
    "imgUrl": cdnBase + "BB1-005.webp",
    "cardType": "Digi-Egg",
    "color": ["Black"],
    "cardNumber": "BB1-005",
    "stage": "In-Training",
    "digiType": ["Lesser", "X Antibody", "CT"],
    "level": 2,
    "inheritedEffect": "[Your Turn] [Once Per Turn] When you play a Digimon with the [CT] trait or use an Option card with the [CT] trait, ＜Draw 1＞.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-002",
    "name": "Tsunomon",
    "imgUrl": cdnBase + "BB1-002.webp",
    "cardType": "Digi-Egg",
    "color": ["Blue"],
    "cardNumber": "BB1-002",
    "stage": "In-Training",
    "digiType": ["Lesser", "IADA"],
    "level": 2,
    "inheritedEffect": "[Your Turn] [Once Per Turn] When any of your Tamers with the [IADA] trait suspend, ＜Draw 1＞.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-003",
    "name": "Nyaromon",
    "imgUrl": cdnBase + "BB1-003.webp",
    "cardType": "Digi-Egg",
    "color": ["Yellow"],
    "cardNumber": "BB1-003",
    "stage": "In-Training",
    "digiType": ["Lesser", "Arena"],
    "level": 2,
    "inheritedEffect": "[All Turns] [Once Per Turn] When a card is removed from your security stack, this Digimon gets +2000 DP for the turn.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-007",
    "name": "Agumon",
    "imgUrl": cdnBase + "BB1-007.webp",
    "cardType": "Digimon",
    "color": ["Red", "Yellow"],
    "cardNumber": "BB1-007",
    "digivolveConditions": [
      { "color": "Red", "level": 2, "cost": 1 },
      { "color": "Yellow", "level": 2, "cost": 1 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[IADA] or [Nerds] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Reptile", "Nerds", "IADA"],
    "attribute": "Vaccine",
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[On Play] Reveal the top 3 cards of your deck, add one card with the [Nerds] or [IADA] trait to your hand. Send the remaining cards to the bottom of the deck.\n[Your Turn] While your opponent has a Digimon with 10000 DP or more and you have [Nathan James], this Digimon may digivolve into [WarGreymon] with the [Nerds] or [IADA] trait in your hand for a digivolution cost of 4, ignoring digivolution requirements.",
    "inheritedEffect": "[When Attacking] [Once Per Turn] 1 of your opponent's Digimon gets -2000 DP for the turn.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-024",
    "name": "Gabumon",
    "imgUrl": cdnBase + "BB1-024.webp",
    "cardType": "Digimon",
    "color": ["Blue", "Green"],
    "cardNumber": "BB1-024",
    "digivolveConditions": [
      { "color": "Blue", "level": 2, "cost": 1 },
      { "color": "Green", "level": 2, "cost": 1 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[IADA]/[Nerds] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Reptile", "Nerds", "IADA"],
    "attribute": "Data",
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[On Play] By trashing 1 card with the [Nerds] or [IADA] trait from your hand, ＜Draw 2＞.\n[Your Turn] While your opponent has a Digimon with 10000 DP or more and you have [Nathan James] in play, this Digimon can digivolve into [MetalGarurumon] with the [Nerds] or [IADA] trait in your hand for a digivolution cost of 4, ignoring digivolution requirements.",
    "inheritedEffect": "[When Attacking] [Once Per Turn] If you have 7 or fewer cards in your hand, ＜Draw 1＞.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-025",
    "name": "Gabumon",
    "imgUrl": cdnBase + "BB1-025.webp",
    "cardType": "Digimon",
    "color": ["Blue", "Black"],
    "cardNumber": "BB1-025",
    "digivolveConditions": [
      { "color": "Blue", "level": 2, "cost": 1 },
      { "color": "Black", "level": 2, "cost": 1 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[IADA] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Reptile", "IADA"],
    "attribute": "Data",
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[Start of Your Main Phase] If you have a Tamer with the [IADA] trait, gain 1 memory and ＜Draw 1＞.",
    "inheritedEffect": "[Your Turn] [Once Per Turn] When a Tamer card with the [IADA] trait is played, ＜Draw 1＞.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-010",
    "name": "Dracmon",
    "imgUrl": cdnBase + "BB1-010.webp",
    "cardType": "Digimon",
    "color": ["Red", "Purple"],
    "cardNumber": "BB1-010",
    "digivolveConditions": [
      { "color": "Red", "level": 2, "cost": 1 },
      { "color": "Purple", "level": 2, "cost": 1 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[Girlies] or [Evil] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Undead", "Girlies"],
    "attribute": "Virus",
    "dp": 1000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[On Play] By trashing 1 card from your hand, you may return 1 Digimon card with [Evil Dragon] in its text, or 1 Digimon card with the [Girlies] trait, from your trash to your hand.",
    "rule": "This card is also treated as having the [Evil] trait.",
    "inheritedEffect": "[On Deletion] Gain 1 memory.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-053",
    "name": "Wormmon",
    "imgUrl": cdnBase + "BB1-053.webp",
    "cardType": "Digimon",
    "color": ["Green", "Purple"],
    "cardNumber": "BB1-053",
    "digivolveConditions": [
      { "color": "Green", "level": 2, "cost": 1 },
      { "color": "Purple", "level": 2, "cost": 1 }
    ],
    "specialDigivolve": "[Digivolve] from [Minomon] or Lv.2 w/[Nerds] or [Arena] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Larva", "Arena", "Nerds"],
    "attribute": "Free",
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[On Play] [When Moving] By trashing 1 card in your hand, suspend 1 Digimon. Then, 1 of your Digimon gains ＜Retaliate＞ until the end of your opponent's turn.",
    "inheritedEffect": "[When Attacking] [Once Per Turn] ＜Draw 1＞. Then, trash 1 card in your hand.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- CHAMPIONS & ULTIMATES ---
  {
    "uniqueCardNumber": "BB1-012",
    "name": "Greymon",
    "imgUrl": cdnBase + "BB1-012.webp",
    "cardType": "Digimon",
    "color": ["Red", "Yellow"],
    "cardNumber": "BB1-012",
    "digivolveConditions": [
      { "color": "Red", "level": 3, "cost": 3 },
      { "color": "Yellow", "level": 3, "cost": 3 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Nerds] or [IADA] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Dinosaur", "Nerds", "IADA"],
    "attribute": "Vaccine",
    "dp": 5000,
    "playCost": 5,
    "level": 4,
    "mainEffect": "[On Play] [When Digivolving] You may play 1 Tamer card with the [Nerds] or [IADA] trait from your hand without paying its memory cost. This effect cannot play a Tamer card with the same name as any of your Tamers in play. Then, if you have [Nathan James] in play, 1 of your opponent's Digimon gets -3000 DP for the turn.",
    "inheritedEffect": "[Your Turn] This Digimon gets +2000 DP.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-026",
    "name": "Garurumon",
    "imgUrl": cdnBase + "BB1-026.webp",
    "cardType": "Digimon",
    "color": ["Blue", "Green"],
    "cardNumber": "BB1-026",
    "digivolveConditions": [
      { "color": "Blue", "level": 3, "cost": 3 },
      { "color": "Green", "level": 3, "cost": 3 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Nerds] or [IADA] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Beast", "Nerds", "IADA"],
    "attribute": "Data",
    "dp": 5000,
    "playCost": 5,
    "level": 4,
    "mainEffect": "[On Play] [When Digivolving] You may play 1 Tamer card with the [Nerds] or [IADA] trait from your hand without paying its memory cost. This effect cannot play a Tamer card with the same name as any of your Tamers in play. Then, if you have [Nathan James] in play, one of your opponent's cards cannot unsuspend during your opponent's next unsuspend phase.",
    "inheritedEffect": "[Your Turn] [Once Per Turn] When a Digimon card with the [IADA] or [Nerds] trait is played, ＜Draw 1＞.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-027",
    "name": "Garurumon",
    "imgUrl": cdnBase + "BB1-027.webp",
    "cardType": "Digimon",
    "color": ["Blue", "Black"],
    "cardNumber": "BB1-027",
    "digivolveConditions": [
      { "color": "Blue", "level": 3, "cost": 3 },
      { "color": "Black", "level": 3, "cost": 3 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[IADA] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Beast", "IADA"],
    "attribute": "Vaccine",
    "dp": 5000,
    "playCost": 5,
    "level": 4,
    "mainEffect": "[On Play] [When Digivolving] You may play 1 Tamer card with the [IADA] trait from your hand without paying the cost. This effect cannot play a Tamer card with the same name as any of your Tamers, except [Director Watanabe]. Then, if you have [Director Watanabe], ＜Draw 1＞.",
    "inheritedEffect": "[Your Turn] [Once Per Turn] When a Tamer card with the [IADA] trait is played, ＜Draw 1＞.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-028",
    "name": "Greymon",
    "imgUrl": cdnBase + "BB1-028.webp",
    "cardType": "Digimon",
    "color": ["Blue"],
    "cardNumber": "BB1-028",
    "digivolveConditions": [{ "color": "Blue", "level": 2, "cost": 2 }],
    "specialDigivolve": "[Digivolve] 2 from Blue [Gaossmon]",
    "stage": "Champion",
    "digiType": ["Dinosaur"],
    "attribute": "Virus",
    "dp": 5000,
    "playCost": 5,
    "level": 4,
    "mainEffect": "[On Play] [When Digivolving] You may reveal the top 4 cards of your deck. Add to your hand 1 Blue Digimon with [Greymon] in its name and 1 [Laura Loath]. Place the rest at the bottom of the deck in any order.",
    "inheritedEffect": "[All Turns] [Once Per Turn] If a Digimon is deleted, you may play 1 [Laura Loath] from your hand without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-041",
    "name": "Sistermon Ciel",
    "imgUrl": cdnBase + "BB1-041.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "BB1-041",
    "digivolveConditions": [{ "color": "Yellow", "level": 3, "cost": 2 }],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[DC] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Puppet", "DC"],
    "attribute": "Vaccine",
    "dp": 5000,
    "playCost": 5,
    "level": 4,
    "mainEffect": "[When Digivolving] You may play 1 Tamer card with the [DC] trait from your hand without paying the cost. For the turn, the Tamer played by this effect is also treated as a 4000 DP Digimon and cannot digivolve.",
    "inheritedEffect": "＜Alliance＞",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-056",
    "name": "Stingmon",
    "imgUrl": cdnBase + "BB1-056.webp",
    "cardType": "Digimon",
    "color": ["Green", "Purple"],
    "cardNumber": "BB1-056",
    "digivolveConditions": [
      { "color": "Green", "level": 3, "cost": 2 },
      { "color": "Purple", "level": 3, "cost": 2 }
    ],
    "specialDigivolve": "[Digivolve] from [Wormmon] or Lv.3 w/[Arena] or [Nerds] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Insectoid", "Arena", "Nerds"],
    "attribute": "Free",
    "dp": 4000,
    "playCost": 5,
    "level": 4,
    "mainEffect": "[When Attacking] If this Digimon attacks an opponent's Digimon, this Digimon may digivolve into a Digimon card with the [Arena] or [Nerds] trait or with [Dinobeemon] in its name in your trash with its digivolution cost reduced by 1.",
    "inheritedEffect": "[When Attacking] [Once Per Turn] ＜Draw 1＞. Then, trash 1 card in your hand.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-043",
    "name": "Lynxmon",
    "imgUrl": cdnBase + "BB1-043.webp",
    "cardType": "Digimon",
    "color": ["Yellow", "Red"],
    "cardNumber": "BB1-043",
    "digivolveConditions": [
      { "color": "Yellow", "level": 3, "cost": 3 },
      { "color": "Red", "level": 3, "cost": 3 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Arena] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Beast", "Arena"],
    "attribute": "Free",
    "dp": 6000,
    "playCost": 6,
    "level": 4,
    "mainEffect": "＜Armor Purge＞ ＜Barrier＞\n[End of Attack] [Once Per Turn] This Digimon may digivolve into a Digimon card in your hand with the [Arena], [Angel], or [Holy Beast] trait with its digivolution cost reduced by 1.",
    "inheritedEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- ULTIMATES (LEVEL 5) ---
  {
    "uniqueCardNumber": "BB1-016",
    "name": "MetalGreymon",
    "imgUrl": cdnBase + "BB1-016.webp",
    "cardType": "Digimon",
    "color": ["Red", "Black"],
    "cardNumber": "BB1-016",
    "digivolveConditions": [
      { "color": "Red", "level": 4, "cost": 4 },
      { "color": "Black", "level": 4, "cost": 4 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[Nerds] or [IADA] trait: 3 cost",
    "stage": "Ultimate",
    "digiType": ["Cyborg", "Nerds", "IADA"],
    "attribute": "Vaccine",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "＜Blocker＞\n[When Attacking] [Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand with its play cost reduced by 2.\n[Your Turn] When another Digimon's attack ends, if this Digimon was suspended by ＜Alliance＞ for that attack, this Digimon may digivolve into a [Nerds] trait Digimon card in the hand with the cost reduced by 2.",
    "inheritedEffect": "＜Alliance＞",
    "assembly": "[Assembly\u00a0-2] Level 4 or lower Digimon card with the [Nerds] trait",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-033",
    "name": "WereGarurumon",
    "imgUrl": cdnBase + "BB1-033.webp",
    "cardType": "Digimon",
    "color": ["Blue", "Green"],
    "cardNumber": "BB1-033",
    "digivolveConditions": [
      { "color": "Blue", "level": 4, "cost": 4 },
      { "color": "Green", "level": 4, "cost": 4 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[Nerds] or [IADA] trait: 3 cost",
    "stage": "Ultimate",
    "digiType": ["Beastkin", "Nerds", "IADA"],
    "attribute": "Vaccine",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "＜Evade＞\n[When Attacking] [Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your trash with its play cost reduced by 2.\n[Your Turn] When another Digimon's attack ends, if this Digimon was suspended by ＜Alliance＞ for that attack, this Digimon may digivolve into a [Nerds] trait Digimon card in the hand with the cost reduced by 2.",
    "inheritedEffect": "＜Alliance＞",
    "assembly": "[Assembly\u00a0-2] Level 4 or lower Digimon card with the [Nerds] trait",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-058",
    "name": "Dinobeemon (X Antibody)",
    "imgUrl": cdnBase + "BB1-058.webp",
    "cardType": "Digimon",
    "color": ["Green", "Purple"],
    "cardNumber": "BB1-058",
    "digivolveConditions": [
      { "color": "Green", "level": 4, "cost": 5 },
      { "color": "Purple", "level": 4, "cost": 5 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[Nerds] or [Arena] trait: 4 cost / [Dinobeemon]: 0 cost",
    "stage": "Ultimate",
    "digiType": ["Mutant", "Arena", "Nerds", "X Antibody"],
    "attribute": "Free",
    "dp": 8000,
    "playCost": 8,
    "level": 5,
    "mainEffect": "＜Vortex＞\n[When Digivolving] Suspend 1 of your opponent's Digimon or Tamers. Then, if [Dinobeemon] is in this Digimon's digivolution cards or it digivolved from the trash, you may play 1 Level 3 or lower Digimon card with the [Nerds], [Arena], or [Free] trait from your trash without paying its memory cost.",
    "rule": "Treat this card as also having the [Insectoid] and [Mythical Dragon] traits.",
    "inheritedEffect": "[Your Turn] [Once Per Turn] When this Digimon attacks an opponent's Digimon, you may play 1 Level 3 or lower Digimon card with the [Nerds], [Arena], or [Free] trait from your trash without paying its memory cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-068",
    "name": "Cerberumon: Werewolf Mode",
    "imgUrl": cdnBase + "BB1-068.webp",
    "cardType": "Digimon",
    "color": ["Purple"],
    "cardNumber": "BB1-068",
    "digivolveConditions": [{ "color": "Purple", "level": 4, "cost": 4 }],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[CT] trait: 3/[WereGarurumon] w/[CT] trait: 1 cost",
    "stage": "Ultimate",
    "digiType": ["Wizard", "CT"],
    "attribute": "Virus",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "[When Digivolving] You may place 1 card with the [CT] trait from your hand or trash under this Digimon as its bottom digivolution card. Then, if this Digimon has 5 or more digivolution cards ＜De-Digivolve 1＞ on 1 of your opponents Digimon.",
    "inheritedEffect": "[All Turns] While this Digimon has the [CT] trait, it gains ＜Scapegoat＞.",
    "assembly": "[Assembly\u00a0-2] 1 Digimon cards with the [CT] trait",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-069",
    "name": "MetalGreymon",
    "imgUrl": cdnBase + "BB1-069.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "BB1-069",
    "digivolveConditions": [{ "color": "Black", "level": 4, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[Three Musketeers] in text: 3 cost",
    "stage": "Ultimate",
    "digiType": ["Cyborg"],
    "attribute": "Virus",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "[On Play] [When Digivolving] By returning 3 cards with [Three Musketeers] in their text from your trash to the top of your deck, gain 1 memory.\n[When Digivolving] [When Attacking] [Once Per Turn] By trashing 1 Option card from any of your Digimon's digivolution cards, delete 1 of your opponent's Digimon with a play cost of 5 or lower.",
    "inheritedEffect": "[All Turns] [Once Per Turn] When Option cards are trashed from this Digimon's digivolution cards, ＜De-Digivolve 1＞ 1 of your opponent's Digimon.",
    "assembly": "[Assembly\u00a0-2] Option card with the [Three Musketeers] trait",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-070",
    "name": "Rebellimon",
    "imgUrl": cdnBase + "BB1-070.webp",
    "cardType": "Digimon",
    "color": ["Black", "Purple"],
    "cardNumber": "BB1-070",
    "digivolveConditions": [
      { "color": "Black", "level": 4, "cost": 4 },
      { "color": "Purple", "level": 4, "cost": 4 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[ME] trait: 3 cost",
    "dnaDigivolve": "[DNA Digivolve] [Black]/[Red] Lv.4 + [Purple]/[Yellow] Lv.4\u00a0: Cost 0",
    "stage": "Ultimate",
    "digiType": ["Cyborg", "ME"],
    "attribute": "Virus",
    "dp": 8000,
    "playCost": 8,
    "level": 5,
    "mainEffect": "＜Collision＞ ＜Piercing＞\n[On Play] [When Digivolving] Reveal the top 3 cards of your deck. Then, delete 1 of your opponent's Digimon with a play cost of 5 or lower. For each card with the [ME] trait revealed, add 1 to the maximum play cost this effect can delete. Trash the revealed cards.\n[All Turns] [Once Per Turn] When any of your cards with the [ME] trait are trashed from your revealed cards, 1 of your other Level 5 or lower Digimon with the [ME] trait may digivolve into 1 of those trashed cards without paying the cost.",
    "inheritedEffect": "[All Turns] [Once Per Turn] When cards are trashed from this [ME] trait Digimon's digivolution cards or your revealed cards, ＜De-Digivolve 1＞ 1 of your opponent's Digimon.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-059",
    "name": "The Raven",
    "imgUrl": cdnBase + "BB1-059.webp",
    "cardType": "Digimon",
    "color": ["Green", "Purple"],
    "cardNumber": "BB1-059",
    "digivolveConditions": [
      { "color": "Green", "level": 4, "cost": 3 },
      { "color": "Purple", "level": 4, "cost": 3 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[DC] trait: 3 cost",
    "stage": "Ultimate",
    "digiType": ["Avian", "DC"],
    "attribute": "Vaccine",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "＜Fortitude＞\n[On Play] [When Digivolving] Suspend 1 of your opponent's Tamers. Then, 1 of your opponent's Tamers cannot unsuspend until the end of your opponent's turn.\n[All Turns] [Once Per Turn] When an opponent's Tamer becomes suspended, you may trash the top card of your opponent's deck for every 2 of their suspended Tamers.",
    "inheritedEffect": "[All Turns] [Once Per Turn] When an opponent's Tamer becomes suspended, trash your opponent's top security card.",
    "rule": "Treat this card as having the name [Crowmon].",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- MEGAS (LEVEL 6) ---
  {
    "uniqueCardNumber": "BB1-061",
    "name": "GranKuwagamon",
    "imgUrl": cdnBase + "BB1-061.webp",
    "cardType": "Digimon",
    "color": ["Green", "Black"],
    "cardNumber": "BB1-061",
    "digivolveConditions": [
      { "color": "Green", "level": 5, "cost": 4 },
      { "color": "Black", "level": 5, "cost": 4 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Dinobeemon] in its name or w/[Nerds] or [Arena] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Insectoid", "Arena", "Nerds"],
    "attribute": "Free",
    "dp": 12000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "＜Armor Purge＞ ＜Piercing＞\n[When Digivolving] Play 1 Level 4 or lower Digimon card with the [Nerds], [Arena], or [Free] trait from your trash without paying its memory cost, or play 1 [Drone] Token to your opponent's field suspended (Digimon/Lv.1/Green/Insectoid/2000 DP/This Digimon cannot unsuspend. On Deletion: Suspend 1 of your Digimon). Then, by placing 1 [GrandisKuwagamon] from your trash as this Digimon's top digivolution card, this Digimon may attack.\n[End of Attack] By placing this Digimon's top stacked card as its bottom digivolution card, unsuspend this Digimon.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-019",
    "name": "MagnaKidmon",
    "imgUrl": cdnBase + "BB1-019.webp",
    "cardType": "Digimon",
    "color": ["Red"],
    "cardNumber": "BB1-019",
    "digivolveConditions": [{ "color": "Red", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[IADA] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Dragonkin", "IADA"],
    "attribute": "Virus",
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "＜Rush＞ ＜Raid＞\n[On Play] [When Attacking] Delete 1 of your opponent's lowest DP Digimon. If this effect didn't delete, 1 of your Digimon with the [IADA] trait is unaffected by your opponent's Option cards and its DP cannot be reduced until the end of your opponent's turn.\n[All Turns] For each of your Tamers with the [IADA] trait and different names, this Digimon gets +1000 DP.",
    "digiXros": "[DigiXros\u00a0-2] Lv.5 or lower Digimon cards with the [IADA] trait and different levels",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-019_P1",
    "name": "MagnaKidmon",
    "imgUrl": cdnBase + "BB1-019_P1.webp",
    "cardType": "Digimon",
    "color": ["Red"],
    "cardNumber": "BB1-019",
    "digivolveConditions": [{ "color": "Red", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[IADA] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Dragonkin", "IADA"],
    "attribute": "Virus",
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "＜Rush＞ ＜Raid＞\n[On Play] [When Attacking] Delete 1 of your opponent's lowest DP Digimon. If this effect didn't delete, 1 of your Digimon with the [IADA] trait is unaffected by your opponent's Option cards and its DP cannot be reduced until the end of your opponent's turn.\n[All Turns] For each of your Tamers with the [IADA] trait and different names, this Digimon gets +1000 DP.",
    "digiXros": "[DigiXros\u00a0-2] Lv.5 or lower Digimon cards with the [IADA] trait and different levels",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-049",
    "name": "LovelyAngemon",
    "imgUrl": cdnBase + "BB1-049.webp",
    "cardType": "Digimon",
    "color": ["Yellow", "Black"],
    "cardNumber": "BB1-049",
    "digivolveConditions": [
      { "color": "Yellow", "level": 5, "cost": 5 },
      { "color": "Black", "level": 5, "cost": 5 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Arena] trait: 4 cost",
    "stage": "Mega",
    "digiType": ["Warrior", "Arena"],
    "attribute": "Vaccine",
    "dp": 12000,
    "playCost": 12,
    "level": 6,
    "mainEffect": "＜Collision＞ ＜Barrier＞ ＜Piercing＞ ＜Blocker＞\n[All Turns] [Once Per Turn] When this Digimon would leave the battle area other than by battle, by trashing your top security card, it does not leave.\n[All Turns] [Once Per Turn] When a card is removed from your security stack, this Digimon gets +3000 DP until the end of your opponent's turn. Then, this Digimon may battle 1 of your opponent's Digimon.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- OPTIONS & LINK CARDS ---
  {
    "uniqueCardNumber": "BB1-096",
    "name": "Driver City",
    "imgUrl": cdnBase + "BB1-096.webp",
    "cardType": "Option",
    "color": ["Yellow", "Green"],
    "cardNumber": "BB1-096",
    "digiType": ["DC"],
    "playCost": 3,
    "mainEffect": "＜Use Req. ([DC] trait)＞\n[Security] [All Turns] All of your Digimon with the [DC] trait gain ＜Barrier＞ and ＜Piercing＞. All of your Tamers with the [DC] trait gain ＜Rush＞.\n[Main] Add your bottom security card to your hand and place this card face up as your bottom security card. Then, you may play 1 Digimon card with the [DC] trait from your hand with its play cost reduced by 3.",
    "securityEffect": "[Security] You may play 1 Level 4 or lower Digimon card with the [DC] trait from your hand or trash without paying its memory cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-097",
    "name": "Digimon Wrestling Belt",
    "imgUrl": cdnBase + "BB1-097.webp",
    "cardType": "Option",
    "color": ["Blue", "Green"],
    "cardNumber": "BB1-097",
    "digiType": ["Arena"],
    "playCost": 3,
    "mainEffect": "＜Use Req. ([Arena] trait)＞\n[Main] Unsuspend 1 of your Digimon. Then, you may link this card to 1 of your Digimon without paying the cost.",
    "securityEffect": "[Security] Suspend 1 of your opponent's Digimon. Then, add this card to your hand.",
    "linkDP": 3000,
    "linkEffect": "[All Turns] [Once Per Turn] When this Digimon wins a battle, trash the top card of your opponent's security stack.",
    "linkRequirement": "[Link] [Arena] trait: 2 cost",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-098",
    "name": "Deep Network",
    "imgUrl": cdnBase + "BB1-098.webp",
    "cardType": "Option",
    "color": ["Blue", "Purple"],
    "cardNumber": "BB1-098",
    "digiType": ["CT"],
    "playCost": 5,
    "mainEffect": "＜Use Req. ([CT] trait)＞\n[Security] [All Turns] [Once Per Turn] When 1 of your Level 6 or higher Digimon with the [CT] trait would be deleted, you may play 1 Level 5 or lower Digimon card with the [CT] trait from that Digimon's digivolution cards without paying the cost.\n[Main] Add your bottom security card to your hand and place this card face up as your bottom security card. Then, you may play 1 [CT] trait Digimon card from your hand with its play cost reduced by 3.",
    "securityEffect": "[Security] You may play 1 Level 4 or lower Digimon card with the [CT] trait from your hand or trash without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-094",
    "name": "Nerds Assemble",
    "imgUrl": cdnBase + "BB1-094.webp",
    "cardType": "Option",
    "color": ["Red", "Green", "Yellow"],
    "cardNumber": "BB1-094",
    "digiType": ["Nerds"],
    "playCost": 3,
    "mainEffect": "＜Use Req. ([Nerds] trait)＞\n[Main] Reveal the top 3 cards of your deck. Add 1 card with the [Nerds] trait from among them to your hand. Return the remaining cards to the bottom of the deck.\n[Main] ＜Delay＞\n• Gain 2 memory.",
    "securityEffect": "[Security] Place this card in the battle area.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-099",
    "name": "Hell Training",
    "imgUrl": cdnBase + "BB1-099.webp",
    "cardType": "Option",
    "color": ["Purple"],
    "cardNumber": "BB1-099",
    "digiType": ["Girlies"],
    "playCost": 2,
    "mainEffect": "＜Use Req. ([Girlies] trait)＞\n[Main] Reveal the top 2 cards of your deck. You may trash 1 [Girlies] trait card from among them. Return the rest to the bottom of the deck.\n[Main] ＜Delay＞\n• 1 of your Digimon may digivolve into a [Girlies] trait Digimon card in your trash with the cost reduced by 2.",
    "securityEffect": "[Security] You may trash 1 card in your hand. Then, place this card in the battle area.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-100",
    "name": "Puppetmaster",
    "imgUrl": cdnBase + "BB1-100.webp",
    "cardType": "Option",
    "color": ["Purple", "Blue"],
    "cardNumber": "BB1-100",
    "digiType": ["CT"],
    "playCost": 4,
    "mainEffect": "＜Use Req. ([CT] trait)＞\n[Main] By trashing 1 card with the [CT] trait in your hand, place this card in the battle area.\n[Opponent's Turn] When an opponent's Digimon attacks while you have a level 5 or higher [CT] trait Digimon, ＜Delay＞.\n• The attacking Digimon battles 1 of your opponent's other Digimon. Then, end the attack.",
    "securityEffect": "[Security] Add this card to your hand.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-101",
    "name": "The Fool",
    "imgUrl": cdnBase + "BB1-101.webp",
    "cardType": "Option",
    "color": ["Purple", "Yellow"],
    "cardNumber": "BB1-101",
    "digiType": ["CT"],
    "playCost": 3,
    "mainEffect": "＜Use Req. ([CT] trait)＞\n[Main] You may play 1 [Ghostmon] or 1 [Ridendo Fusco] from your hand or trash without paying its memory cost. Then, place this card in the battle area.\n[All Turns] When one of your Digimon with the [CT] trait would leave the battle area, ＜Delay＞.\n• You may play 1 [Fool] Token. (Digimon//Purple/4000 DP/＜Blocker＞ ＜Retaliate＞) If you do, change its original DP and colors to the original DP and colors of that Digimon.",
    "securityEffect": "[Security] Activate this card's [Main] effect.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-102",
    "name": "Resolution No. 256 of the 65th United Nations General Assembly, Agenda Item No. 102, the Charter of the International Agency of Digital Affairs",
    "imgUrl": cdnBase + "BB1-102.webp",
    "cardType": "Option",
    "color": ["White", "Blue"],
    "cardNumber": "BB1-102",
    "digiType": ["IADA"],
    "playCost": 3,
    "mainEffect": "＜Use Req. ([IADA] trait)＞\n[Main] You may play 1 Tamer card or Level 3 Digimon card with the [IADA] trait from your hand or trash without paying the cost. Then, place this card in the battle area.\n[Your Turn] When any of your Tamers with the [IADA] trait suspend, ＜Delay＞.\n• 1 of your Digimon with the [IADA] trait may digivolve into a Digimon card with the [IADA] trait with its digivolution cost reduced by 1. For each of your Tamers with the [IADA] trait with different names, further reduce the cost by 1.",
    "securityEffect": "[Security] Activate this card's [Main] effect.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "SC1-078",
    "name": "Der Freischütz",
    "imgUrl": cdnBase + "SC1-078.webp",
    "cardType": "Option",
    "color": ["Purple", "Black"],
    "cardNumber": "SC1-078",
    "digiType": ["CT"],
    "playCost": 6,
    "mainEffect": "＜Use Req. ([CT] trait)＞\n[Main] You may play 1 Digimon card with the [CT] trait from your trash with its play cost reduced by 4. Then, ＜De-Digivolve 1＞ on 1 of your opponent's Digimon for each Digimon you have in play. Then, place this card as the bottom digivolution card of 1 of your Digimon with the [CT] trait.",
    "securityEffect": "[Security] You may play 1 Level 4 or lower Digimon card with the [CT] trait from your hand or trash without paying its memory cost. Then, add this card to your hand.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- FULL ST01 SET ---
  {
    "uniqueCardNumber": "ST01-01",
    "name": "Hopmon",
    "imgUrl": cdnBase + "ST01-01.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-01",
    "stage": "In-Training",
    "digiType": ["Lesser", "Nikari"],
    "level": 2,
    "inheritedEffect": "[All Turns] [Once Per Turn] When an opponent's Digimon is deleted, ＜Draw 1＞.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-02",
    "name": "Salamon",
    "imgUrl": cdnBase + "ST01-02.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-02",
    "digivolveConditions": [{ "color": "Yellow", "level": 2, "cost": 0 }],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[Nikari] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Mammal", "Nikari"],
    "attribute": "Vaccine",
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[On Play] [Start of Your Main Phase] One of your Digimon with the [Nikari] trait may digivolve into a Yellow or Black Digimon card with the [Nikari] trait in your hand with its digivolution cost reduced by 1.",
    "inheritedEffect": "[Your Turn] Your opponent's security Digimon get -3000 DP.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "gusart.22",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-03",
    "name": "Gatomon",
    "imgUrl": cdnBase + "ST01-03.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-03",
    "digivolveConditions": [{ "color": "Yellow", "level": 3, "cost": 2 }],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Nikari] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Holy Beast", "Nikari"],
    "attribute": "Vaccine",
    "dp": 4000,
    "playCost": 4,
    "level": 4,
    "mainEffect": "[When Digivolving] If you have 1 or fewer Tamers, you may play 1 Tamer card with the [Nikari] trait from your hand without paying its memory cost.",
    "inheritedEffect": "[Your Turn] Your opponent's security Digimon get -3000 DP.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Lacapiart",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-04",
    "name": "Angewomon",
    "imgUrl": cdnBase + "ST01-04.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-04",
    "digivolveConditions": [{ "color": "Yellow", "level": 4, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[Nikari] trait: 3 cost",
    "stage": "Ultimate",
    "digiType": ["Archangel", "Nikari"],
    "attribute": "Vaccine",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "＜Alliance＞\n[On Play] [When Digivolving] [When Attacking] 1 of your opponent's Digimon gets -4000 DP until the end of their turn.\n[End of Your Turn] This Digimon and 1 of your other Digimon with the [Nikari] trait in play may DNA digivolve into a Digimon card with the [Nikari] trait in your hand.",
    "inheritedEffect": "＜Alliance＞",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-05",
    "name": "Magnadramon",
    "imgUrl": cdnBase + "ST01-05.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-05",
    "digivolveConditions": [{ "color": "Yellow", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Nikari] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Holy Dragon", "Four Great Dragons", "Nikari"],
    "attribute": "Vaccine",
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "＜Barrier＞ ＜Ascension＞\n[On Play] [When Digivolving] 1 of your other Digimon with the [Nikari] trait may digivolve into a Level 5 or lower Black Digimon card with the [Nikari] trait in your hand without paying its memory cost. Your opponent's Digimon effects do not affect your Black Digimon with the [Nikari] trait until the end of their turn.\n[When Digivolving] [End of Attack] If you have 1 or fewer security cards, this Digimon may digivolve into [Nyabootmon] in your hand with its digivolution cost reduced by 1.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-06",
    "name": "Nyabootmon",
    "imgUrl": cdnBase + "ST01-06.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-06",
    "digivolveConditions": [{ "color": "Yellow", "level": 6, "cost": 4 }],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nikari] trait: 4 cost",
    "stage": "Mega",
    "digiType": ["Puppet", "Nikari"],
    "attribute": "Vaccine",
    "dp": 14000,
    "playCost": 14,
    "level": 7,
    "mainEffect": "＜Piercing＞ ＜Engage＞\n[When Digivolving] This Digimon may unsuspend.\n[When Digivolving] [When Attacking] [Once Per Turn] If you have a [Kari Kamiya] in play, trash your opponent's top security card.\n[End of Attack] If you have 2 or fewer security cards, ＜Recovery +1 (Deck)＞. Then, 1 of your opponent's Digimon gets -6000 DP, and all of your opponent's Digimon get -3000 DP for each card in your security stack until the end of their turn.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-07",
    "name": "Dagger",
    "imgUrl": cdnBase + "ST01-07.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-07",
    "digivolveConditions": [{ "color": "Black", "level": 2, "cost": 0 }],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[Nikari] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Mini Dragon", "Nikari"],
    "attribute": "Vaccine",
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[On Play] [When Moving] 1 of your Digimon with the [Nikari] trait gets +4000 DP until the end of your opponent's turn.\n[Your Turn] If your opponent has a Digimon with 10000 DP or more, by placing 1 [Nico Kärnä] from your hand or battle area under this Digimon as its bottom digivolution card, this Digimon may digivolve into [Fujinmon] in your hand for a digivolution cost of 4, ignoring digivolution requirements. When this Digimon would digivolve into [Fujinmon] by this effect, this Digimon cannot have its DP reduced by your opponent's effects until the end of your opponent's turn.\n[Rule] Treat this card as having the name [Monodramon]",
    "inheritedEffect": "[End of Attack] [Once Per Turn] If this Digimon's attack target was an opponent's Digimon, ＜Draw 1＞.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-08",
    "name": "Strikedramon",
    "imgUrl": cdnBase + "ST01-008.webp",
    "cardType": "Digimon",
    "color": ["Blue"],
    "cardNumber": "ST01-08",
    "digivolveConditions": [{ "color": "Blue", "level": 3, "cost": 2 }],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Nikari] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Dragonkin", "Nikari"],
    "attribute": "Vaccine",
    "dp": 5000,
    "playCost": 5,
    "level": 4,
    "mainEffect": "[Main] [Once Per Turn] You may play or use 1 card with the [Nikari] trait from your hand or trash with its play cost or use cost reduced by 2.",
    "inheritedEffect": "[Your Turn] If you have Tamers in play with 2 or more different names, this Digimon gets +3000 DP.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-009",
    "name": "Cyberdramon",
    "imgUrl": cdnBase + "ST01-009.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-009",
    "digivolveConditions": [{ "color": "Black", "level": 4, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[Nikari] trait: 3 cost",
    "stage": "Ultimate",
    "digiType": ["Cyborg", "Nikari"],
    "attribute": "Vaccine",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "＜Collision＞\n[On Play] [When Digivolving] You may play 1 [Nico Kärnä] Tamer card from your hand without paying its memory cost.\n[All Turns] When one of your [Kari Kamiya] Tamers or Level 5 or higher Yellow Digimon with the [Nikari] trait would be deleted, this Digimon can digivolve into [Darkdramon] in your hand without paying its digivolution cost. If this Digimon digivolves by this effect, that Tamer or Digimon does not leave the field.",
    "inheritedEffect": "[When Attacking] [Once Per Turn] ＜De-Digivolve 1＞ 1 of your opponent's Digimon.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-010",
    "name": "Darkdramon",
    "imgUrl": cdnBase + "ST01-010.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-010",
    "digivolveConditions": [{ "color": "Black", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Nikari] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Cyborg", "Nikari"],
    "attribute": "Virus",
    "dp": 12000,
    "playCost": 12,
    "level": 6,
    "mainEffect": "＜Collision＞ ＜Reboot＞ ＜Blocker＞\n[When Digivolving] ＜De-Digivolve 2＞ 1 of your opponent's Digimon. Then, if digivolved by a card with the [Nikari] trait's effect, your opponent can't trash the digivolution cards of 1 of your Yellow and 1 of your Black Digimon with the [Nikari] trait until the end of their turn.\n[All Turns] [Once Per Turn] When this Digimon deletes an opponent's Digimon in battle, this Digimon may unsuspend.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-11",
    "name": "Fujinmon",
    "imgUrl": cdnBase + "ST01-11.webp",
    "cardType": "Digimon",
    "color": ["Green"],
    "cardNumber": "ST01-11",
    "digivolveConditions": [{ "color": "Green", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Nikari] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Cyborg", "Nikari"],
    "attribute": "Vaccine",
    "dp": 13000,
    "playCost": 13,
    "level": 6,
    "mainEffect": "＜Blocker＞ ＜Vortex＞ ＜Reboot＞\n[When Digivolving] Suspend 1 of your opponent's Digimon or Tamers. Then, unsuspend 1 of your Digimon.\n[When Attacking] [Once Per Turn] This Digimon may battle 1 of your opponent's Digimon.\n[Your Turn] [Once Per Turn] When this Digimon deletes an opponent's Digimon in battle, if this Digimon has [Nico Kärnä] in its digivolution cards, activate 1 of this Digimon's [When Digivolving] effects.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-12",
    "name": "Kari Kamiya",
    "imgUrl": cdnBase + "ST01-12.webp",
    "cardType": "Tamer",
    "color": ["Yellow"],
    "cardNumber": "ST01-12",
    "digiType": ["Nikari"],
    "playCost": 3,
    "mainEffect": "[Start of Your Main Phase] If you have a Digimon in play, gain 1 memory.\n[All Turns] When one of your Digimon digivolves into a Black Digimon with the [Nikari] trait, you may suspend this Tamer to give that Digimon ＜Barrier＞ until the end of your turn.",
    "securityEffect": "[Security] Play this card without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-13",
    "name": "Nico Kärnä",
    "imgUrl": cdnBase + "ST01-13.webp",
    "cardType": "Tamer",
    "color": ["Yellow"],
    "cardNumber": "ST01-13",
    "digiType": ["Nikari"],
    "playCost": 3,
    "mainEffect": "[Start of Your Main Phase] If your opponent has a Digimon in play, gain 1 memory.\n[All Turns] When one of your Digimon digivolves into a Yellow Digimon with the [Nikari] trait, you may suspend this Tamer to give that Digimon ＜Blocker＞ until the end of your opponent's turn.",
    "inheritedEffect": "＜Piercing＞",
    "securityEffect": "[Security] Play this card without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-14",
    "name": "Erase Claw",
    "imgUrl": cdnBase + "ST01-14.webp",
    "cardType": "Option",
    "color": ["Blue"],
    "cardNumber": "ST01-14",
    "digiType": ["Nikari"],
    "playCost": 6,
    "mainEffect": "＜Use Req. ([Nikari] trait)＞\nWhen this card would be used, if you have a Digimon with [Cyberdramon] in its name and the [Nikari] trait in play, reduce the cost by 2.\n[Main] Choose 1 of the following effects:\n• Delete 1 of your opponent's Level 5 or lower Digimon.\n• Delete 1 of your opponent's Level 6 or higher Digimon. If you do, delete 1 of your Tamers named [Kari Kamiya].",
    "securityEffect": "[Security] Add this card to your hand.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-15",
    "name": "When Dark Meets The Light",
    "imgUrl": cdnBase + "ST01-15.webp",
    "cardType": "Option",
    "color": ["Blue"],
    "cardNumber": "ST01-15",
    "digiType": ["Nikari"],
    "playCost": 3,
    "mainEffect": "＜Use Req. ([Nikari] trait)＞\n[Main] Reveal the top 3 cards of your deck. Add 1 card with the [Nikari] trait from among them to your hand. Return the remaining cards to the bottom of your deck in any order. Then, place this card in the battle area.\n[Main] ＜Delay＞\n• You may play 1 Tamer card with the [Nikari] trait from your hand with its play cost reduced by 3.",
    "securityEffect": "[Security] Activate this card's [Main] effects.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  }
]);

print("Successfully restored all custom BB1, ST01, and SC1 cards on MongoDB Atlas!");
