// ==========================================
// RE-IMPORT SCRIPT MATCHING DISK FILENAMES
// ==========================================

const targetCards = [
  "ST01-01", "ST01-02", "ST01-03", "ST01-04", "ST01-05", 
  "ST01-06", "ST01-07", "ST01-08", "ST01-008", "ST01-009", 
  "ST01-010", "ST01-11", "ST01-12", "ST01-13", "ST01-14", 
  "ST01-15", "BB1-035", "BB1-043", "BB1-085", "BB1-085_P1",
  "BB1-096", "BB1-097", "BB1-098", "BB1-103", "BB1-103_P1", 
  "BB1-103_P2", "BB1-104", "BB1-104_P1", "BB1-104_P2"
];

// Clean up existing records
db.card.deleteMany({ uniqueCardNumber: { $in: targetCards } });

db.card.insertMany([
  // --- ST01 NIKARI LINE (EXACT WEBP MATCH) ---
  {
    "uniqueCardNumber": "ST01-01",
    "name": "Hopmon",
    "imgUrl": "/ST01-01.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-01",
    "digivolveConditions": [],
    "stage": "In-Training",
    "digiType": ["Lesser", "Nikari"],
    "attribute": null,
    "dp": null,
    "playCost": null,
    "level": 2,
    "mainEffect": null,
    "inheritedEffect": "[All Turns] [Once Per Turn] When an opponent's Digimon is deleted, ＜Draw 1＞.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-02",
    "name": "Salamon",
    "imgUrl": "/ST01-02.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-02",
    "digivolveConditions": [{ "color": "Yellow", "level": 2, "cost": 0 }],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[Nikari] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Mammal", "Nikari"],
    "attribute": "Vaccine",
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[On Play] [Start of Your Main Phase] One of your Digimon with the [Nikari] trait may digivolve into a Yellow or Black Digimon card with the [Nikari] trait in your hand with its digivolution cost reduced by 1.",
    "inheritedEffect": "[Your Turn] Your opponent's security Digimon get -3000 DP.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "gusart.22",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-03",
    "name": "Gatomon",
    "imgUrl": "/ST01-03.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-03",
    "digivolveConditions": [{ "color": "Yellow", "level": 3, "cost": 2 }],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Nikari] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Holy Beast", "Nikari"],
    "attribute": "Vaccine",
    "dp": 4000,
    "playCost": 4,
    "level": 4,
    "mainEffect": "[When Digivolving] If you have 1 or fewer Tamers, you may play 1 Tamer card with the [Nikari] trait from your hand without paying its memory cost.",
    "inheritedEffect": "[Your Turn] Your opponent's security Digimon get -3000 DP.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Lacapiart",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-04",
    "name": "Angewomon",
    "imgUrl": "/ST01-04.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-04",
    "digivolveConditions": [{ "color": "Yellow", "level": 4, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[Nikari] trait: 3 cost",
    "stage": "Ultimate",
    "digiType": ["Archangel", "Nikari"],
    "attribute": "Vaccine",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "＜Alliance＞\n[On Play] [When Digivolving] [When Attacking] 1 of your opponent's Digimon gets -4000 DP until the end of their turn.\n[End of Your Turn] This Digimon and 1 of your other Digimon with the [Nikari] trait in play may DNA digivolve into a Digimon card with the [Nikari] trait in your hand.",
    "inheritedEffect": "＜Alliance＞",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-05",
    "name": "Magnadramon",
    "imgUrl": "/ST01-05.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-05",
    "digivolveConditions": [{ "color": "Yellow", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Nikari] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Holy Dragon", "Four Great Dragons", "Nikari"],
    "attribute": "Vaccine",
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "＜Barrier＞ ＜Ascension＞\n[On Play] [When Digivolving] 1 of your other Digimon with the [Nikari] trait may digivolve into a Level 5 or lower Black Digimon card with the [Nikari] trait in your hand without paying its memory cost. Your opponent's Digimon effects do not affect your Black Digimon with the [Nikari] trait until the end of their turn.\n[When Digivolving] [End of Attack] If you have 1 or fewer security cards, this Digimon may digivolve into [Nyabootmon] in your hand with its digivolution cost reduced by 1.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-06",
    "name": "Nyabootmon",
    "imgUrl": "/ST01-06.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-06",
    "digivolveConditions": [{ "color": "Yellow", "level": 6, "cost": 4 }],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nikari] trait: 4 cost",
    "stage": "Mega",
    "digiType": ["Puppet", "Nikari"],
    "attribute": "Vaccine",
    "dp": 14000,
    "playCost": 14,
    "level": 7,
    "mainEffect": "＜Piercing＞ ＜Engage＞\n[When Digivolving] This Digimon may unsuspend.\n[When Digivolving] [When Attacking] [Once Per Turn] If you have a [Kari Kamiya] in play, trash your opponent's top security card.\n[End of Attack] If you have 2 or fewer security cards, ＜Recovery +1 (Deck)＞. Then, 1 of your opponent's Digimon gets -6000 DP, and all of your opponent's Digimon get -3000 DP for each card in your security stack until the end of their turn.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-07",
    "name": "Dagger",
    "imgUrl": "/ST01-07.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-07",
    "digivolveConditions": [{ "color": "Black", "level": 2, "cost": 0 }],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[Nikari] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Mini Dragon", "Nikari"],
    "attribute": "Vaccine",
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[On Play] [When Moving] 1 of your Digimon with the [Nikari] trait gets +4000 DP until the end of your opponent's turn.\n[Your Turn] If your opponent has a Digimon with 10000 DP or more, by placing 1 [Nico Kärnä] from your hand or battle area under this Digimon as its bottom digivolution card, this Digimon may digivolve into [Fujinmon] in your hand for a digivolution cost of 4, ignoring digivolution requirements. When this Digimon would digivolve into [Fujinmon] by this effect, this Digimon cannot have its DP reduced by your opponent's effects until the end of your opponent's turn.\n[Rule] Treat this card as having the name [Monodramon]",
    "inheritedEffect": "[End of Attack] [Once Per Turn] If this Digimon's attack target was an opponent's Digimon, ＜Draw 1＞.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-08",
    "name": "Strikedramon",
    "imgUrl": "/ST01-008.webp", // <-- Matches ST01-008.webp from disk
    "cardType": "Digimon",
    "color": ["Blue"],
    "cardNumber": "ST01-08",
    "digivolveConditions": [{ "color": "Blue", "level": 3, "cost": 2 }],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Nikari] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Dragonkin", "Nikari"],
    "attribute": "Vaccine",
    "dp": 5000,
    "playCost": 5,
    "level": 4,
    "mainEffect": "[Main] [Once Per Turn] You may play or use 1 card with the [Nikari] trait from your hand or trash with its play cost or use cost reduced by 2.",
    "inheritedEffect": "[Your Turn] If you have Tamers in play with 2 or more different names, this Digimon gets +3000 DP.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-009",
    "name": "Cyberdramon",
    "imgUrl": "/ST01-009.webp", // <-- Matches ST01-009.webp
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-009",
    "digivolveConditions": [{ "color": "Black", "level": 4, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[Nikari] trait: 3 cost",
    "stage": "Ultimate",
    "digiType": ["Cyborg", "Nikari"],
    "attribute": "Vaccine",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "＜Collision＞\n[On Play] [When Digivolving] You may play 1 [Nico Kärnä] Tamer card from your hand without paying its memory cost.\n[All Turns] When one of your [Kari Kamiya] Tamers or Level 5 or higher Yellow Digimon with the [Nikari] trait would be deleted, this Digimon can digivolve into [Darkdramon] in your hand without paying its digivolution cost. If this Digimon digivolves by this effect, that Tamer or Digimon does not leave the field.",
    "inheritedEffect": "[When Attacking] [Once Per Turn] ＜De-Digivolve 1＞ 1 of your opponent's Digimon.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-010",
    "name": "Darkdramon",
    "imgUrl": "/ST01-010.webp", // <-- Matches ST01-010.webp
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-010",
    "digivolveConditions": [{ "color": "Black", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Nikari] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Cyborg", "Nikari"],
    "attribute": "Virus",
    "dp": 12000,
    "playCost": 12,
    "level": 6,
    "mainEffect": "＜Collision＞ ＜Reboot＞ ＜Blocker＞\n[When Digivolving] ＜De-Digivolve 2＞ 1 of your opponent's Digimon. Then, if digivolved by a card with the [Nikari] trait's effect, your opponent can't trash the digivolution cards of 1 of your Yellow and 1 of your Black Digimon with the [Nikari] trait until the end of their turn.\n[All Turns] [Once Per Turn] When this Digimon deletes an opponent's Digimon in battle, this Digimon may unsuspend.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-11",
    "name": "Fujinmon",
    "imgUrl": "/ST01-11.webp",
    "cardType": "Digimon",
    "color": ["Green"],
    "cardNumber": "ST01-11",
    "digivolveConditions": [{ "color": "Green", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Nikari] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Cyborg", "Nikari"],
    "attribute": "Vaccine",
    "dp": 13000,
    "playCost": 13,
    "level": 6,
    "mainEffect": "＜Blocker＞ ＜Vortex＞ ＜Reboot＞\n[When Digivolving] Suspend 1 of your opponent's Digimon or Tamers. Then, unsuspend 1 of your Digimon.\n[When Attacking] [Once Per Turn] This Digimon may battle 1 of your opponent's Digimon.\n[Your Turn] [Once Per Turn] When this Digimon deletes an opponent's Digimon in battle, if this Digimon has [Nico Kärnä] in its digivolution cards, activate 1 of this Digimon's [When Digivolving] effects.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-12",
    "name": "Kari Kamiya",
    "imgUrl": "/ST01-12.webp",
    "cardType": "Tamer",
    "color": ["Yellow"],
    "cardNumber": "ST01-12",
    "digivolveConditions": [],
    "digiType": ["Nikari"],
    "playCost": 3,
    "mainEffect": "[Start of Your Main Phase] If you have a Digimon in play, gain 1 memory.\n[All Turns] When one of your Digimon digivolves into a Black Digimon with the [Nikari] trait, you may suspend this Tamer to give that Digimon ＜Barrier＞ until the end of your turn.",
    "securityEffect": "[Security] Play this card without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-13",
    "name": "Nico Kärnä",
    "imgUrl": "/ST01-13.webp",
    "cardType": "Tamer",
    "color": ["Yellow"],
    "cardNumber": "ST01-13",
    "digivolveConditions": [],
    "digiType": ["Nikari"],
    "playCost": 3,
    "mainEffect": "[Start of Your Main Phase] If your opponent has a Digimon in play, gain 1 memory.\n[All Turns] When one of your Digimon digivolves into a Yellow Digimon with the [Nikari] trait, you may suspend this Tamer to give that Digimon ＜Blocker＞ until the end of your opponent's turn.",
    "inheritedEffect": "＜Piercing＞",
    "securityEffect": "[Security] Play this card without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-14",
    "name": "Erase Claw",
    "imgUrl": "/ST01-14.webp",
    "cardType": "Option",
    "color": ["Blue"],
    "cardNumber": "ST01-14",
    "digivolveConditions": [],
    "digiType": ["Nikari"],
    "playCost": 6,
    "mainEffect": "＜Use Req. ([Nikari] trait)＞\nWhen this card would be used, if you have a Digimon with [Cyberdramon] in its name and the [Nikari] trait in play, reduce the cost by 2.\n[Main] Choose 1 of the following effects:\n• Delete 1 of your opponent's Level 5 or lower Digimon.\n• Delete 1 of your opponent's Level 6 or higher Digimon. If you do, delete 1 of your Tamers named [Kari Kamiya].",
    "securityEffect": "[Security] Add this card to your hand.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-15",
    "name": "When Dark Meets The Light",
    "imgUrl": "/ST01-15.webp",
    "cardType": "Option",
    "color": ["Blue"],
    "cardNumber": "ST01-15",
    "digivolveConditions": [],
    "digiType": ["Nikari"],
    "playCost": 3,
    "mainEffect": "＜Use Req. ([Nikari] trait)＞\n[Main] Reveal the top 3 cards of your deck. Add 1 card with the [Nikari] trait from among them to your hand. Return the remaining cards to the bottom of your deck in any order. Then, place this card in the battle area.\n[Main] ＜Delay＞\n• You may play 1 Tamer card with the [Nikari] trait from your hand with its play cost reduced by 3.",
    "securityEffect": "[Security] Activate this card's [Main] effects.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- BB1 CARDS WITH WEBP MATCHES ---
  {
    "uniqueCardNumber": "BB1-035",
    "name": "Metatromon",
    "imgUrl": "/BB1-035.webp",
    "cardType": "Digimon",
    "color": ["Blue", "Black"],
    "cardNumber": "BB1-035",
    "digivolveConditions": [
      { "color": "Blue", "level": 5, "cost": 5 },
      { "color": "Black", "level": 5, "cost": 5 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[IADA] trait: 4 cost",
    "stage": "Mega",
    "digiType": ["Machine", "IADA"],
    "attribute": "Vaccine",
    "dp": 13000,
    "playCost": 13,
    "level": 6,
    "mainEffect": "＜Blocker＞ ＜Decode ([MetalMamemon])＞\nWhen any of your [MetalMamemon] would digivolve into this Digimon card, reduce the digivolution cost by 1 for every 2 of your [IADA] trait Tamers with different names.\n[When Digivolving] [When Attacking] [Once Per Turn] You may play 1 Tamer card with the [IADA] trait from your hand or trash without paying the cost. This effect cannot play a Tamer card with the same name as any of your Tamers in play. Then, if you have [Director Watanabe] in play, return 1 of your opponent's Digimon with the lowest play cost to the bottom of their deck.\n[All Turns] [Once Per Turn] When any of your Tamers with the [IADA] trait are played or suspend, 1 of your opponent's Digimon cannot suspend until the end of your opponent's turn.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-043",
    "name": "Lynxmon",
    "imgUrl": "/BB1-043.webp",
    "cardType": "Digimon",
    "color": ["Yellow", "Red"],
    "cardNumber": "BB1-043",
    "digivolveConditions": [
      { "color": "Yellow", "level": 3, "cost": 3 },
      { "color": "Red", "level": 3, "cost": 3 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Arena] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Beast", "Arena"],
    "attribute": "Free",
    "dp": 6000,
    "playCost": 6,
    "level": 4,
    "mainEffect": "＜Armor Purge＞ ＜Barrier＞\n[End of Attack] [Once Per Turn] This Digimon may digivolve into a Digimon card in your hand with the [Arena], [Angel], or [Holy Beast] trait with its digivolution cost reduced by 1.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-096",
    "name": "Driver City",
    "imgUrl": "/BB1-096.webp",
    "cardType": "Option",
    "color": ["Yellow", "Green"],
    "cardNumber": "BB1-096",
    "digivolveConditions": [],
    "digiType": ["DC"],
    "playCost": 3,
    "mainEffect": "＜Use Req. ([DC] trait)＞\n[Security] [All Turns] All of your Digimon with the [DC] trait gain ＜Barrier＞ and ＜Piercing＞. All of your Tamers with the [DC] trait gain ＜Rush＞.\n[Main] Add your bottom security card to your hand and place this card face up as your bottom security card. Then, you may play 1 Digimon card with the [DC] trait from your hand with its play cost reduced by 3.",
    "securityEffect": "[Security] You may play 1 Level 4 or lower Digimon card with the [DC] trait from your hand or trash without paying its memory cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-097",
    "name": "Digimon Wrestling Belt",
    "imgUrl": "/BB1-097.webp",
    "cardType": "Option",
    "color": ["Blue", "Green"],
    "cardNumber": "BB1-097",
    "digivolveConditions": [],
    "digiType": ["Arena"],
    "playCost": 3,
    "mainEffect": "＜Use Req. ([Arena] trait)＞\n[Main] Unsuspend 1 of your Digimon. Then, you may link this card to 1 of your Digimon without paying the cost.",
    "securityEffect": "[Security] Suspend 1 of your opponent's Digimon. Then, add this card to your hand.",
    "linkDP": 3000,
    "linkEffect": "＜All Turns＞ ＜Once Per Turn＞ When this Digimon wins a battle, trash the top card of your opponent's security stack.",
    "linkRequirement": "[Link] [Arena] trait: 2 cost",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-098",
    "name": "Deep Network",
    "imgUrl": "/BB1-098.webp",
    "cardType": "Option",
    "color": ["Blue", "Purple"],
    "cardNumber": "BB1-098",
    "digivolveConditions": [],
    "digiType": ["CT"],
    "playCost": 5,
    "mainEffect": "＜Use Req. ([CT] trait)＞\n[Security] [All Turns] [Once Per Turn] When 1 of your Level 6 or higher Digimon with the [CT] trait would be deleted, you may play 1 Level 5 or lower Digimon card with the [CT] trait from that Digimon's digivolution cards without paying the cost.\n[Main] Add your bottom security card to your hand and place this card face up as your bottom security card. Then, you may play 1 [CT] trait Digimon card from your hand with its play cost reduced by 3.",
    "securityEffect": "[Security] You may play 1 Level 4 or lower Digimon card with the [CT] trait from your hand or trash without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-103",
    "name": "TyrantKabuterimon",
    "imgUrl": "/BB1-103.webp",
    "cardType": "Digimon",
    "color": ["Green"],
    "cardNumber": "BB1-103",
    "digivolveConditions": [{ "color": "Green", "level": 6, "cost": 6 }],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Insectoid] trait with 13000 DP or less: 3 cost",
    "stage": "Mega",
    "digiType": ["Insectoid", "Nerds", "Arena"],
    "attribute": "Virus",
    "dp": 14000,
    "playCost": 14,
    "level": 7,
    "mainEffect": "＜Vortex＞ ＜Piercing＞\n[When Digivolving] Play 1 [Drone] Token (Green/Digimon/Insectoid/2000 DP/this Digimon cannot unsuspend. On Deletion: Suspend 1 of your opponent's Digimon) to your opponent's field suspended. Then, play up to 5 play cost of Digimon cards with the [Nerds], [Arena], or [Insectoid] traits from your trash without paying their memory costs. For each of your opponent's suspended Digimon, increase the total play cost you can play by 2.\n[All Turns] All of your other Digimon with the [Insectoid], [Arena], or [Nerds] trait gain ＜Retaliate＞.\n[All Turns] [Once Per Turn] When a Digimon is played, 1 of your other Digimon may battle 1 of your opponent's Digimon.\n[Rule] This card is also treated as having the [Free] trait.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-103_P1",
    "name": "TyrantKabuterimon",
    "imgUrl": "/BB1-103_P1.webp",
    "cardType": "Digimon",
    "color": ["Green"],
    "cardNumber": "BB1-103",
    "digivolveConditions": [{ "color": "Green", "level": 6, "cost": 6 }],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Insectoid] trait with 13000 DP or less: 3 cost",
    "stage": "Mega",
    "digiType": ["Insectoid", "Nerds", "Arena"],
    "attribute": "Virus",
    "dp": 14000,
    "playCost": 14,
    "level": 7,
    "mainEffect": "＜Vortex＞ ＜Piercing＞\n[When Digivolving] Play 1 [Drone] Token (Green/Digimon/Insectoid/2000 DP/this Digimon cannot unsuspend. On Deletion: Suspend 1 of your opponent's Digimon) to your opponent's field suspended. Then, play up to 5 play cost of Digimon cards with the [Nerds], [Arena], or [Insectoid] traits from your trash without paying their memory costs. For each of your opponent's suspended Digimon, increase the total play cost you can play by 2.\n[All Turns] All of your other Digimon with the [Insectoid], [Arena], or [Nerds] trait gain ＜Retaliate＞.\n[All Turns] [Once Per Turn] When a Digimon is played, 1 of your other Digimon may battle 1 of your opponent's Digimon.\n[Rule] This card is also treated as having the [Free] trait.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-103_P2",
    "name": "TyrantKabuterimon",
    "imgUrl": "/BB1-103_P2.webp",
    "cardType": "Digimon",
    "color": ["Green"],
    "cardNumber": "BB1-103",
    "digivolveConditions": [{ "color": "Green", "level": 6, "cost": 6 }],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Insectoid] trait with 13000 DP or less: 3 cost",
    "stage": "Mega",
    "digiType": ["Insectoid", "Nerds", "Arena"],
    "attribute": "Virus",
    "dp": 14000,
    "playCost": 14,
    "level": 7,
    "mainEffect": "＜Vortex＞ ＜Piercing＞\n[When Digivolving] Play 1 [Drone] Token (Green/Digimon/Insectoid/2000 DP/this Digimon cannot unsuspend. On Deletion: Suspend 1 of your opponent's Digimon) to your opponent's field suspended. Then, play up to 5 play cost of Digimon cards with the [Nerds], [Arena], or [Insectoid] traits from your trash without paying their memory costs. For each of your opponent's suspended Digimon, increase the total play cost you can play by 2.\n[All Turns] All of your other Digimon with the [Insectoid], [Arena], or [Nerds] trait gain ＜Retaliate＞.\n[All Turns] [Once Per Turn] When a Digimon is played, 1 of your other Digimon may battle 1 of your opponent's Digimon.\n[Rule] This card is also treated as having the [Free] trait.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-104",
    "name": "Omnimon",
    "imgUrl": "/BB1-104.webp",
    "cardType": "Digimon",
    "color": ["White", "Blue", "Red"],
    "cardNumber": "BB1-104",
    "digivolveConditions": [],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nerds] trait: 5 cost",
    "dnaDigivolve": "[DNA Digivolve] [Red]/[Yellow] Lv.6 + [Blue]/[Green] Lv.6\u00a0: Cost 0",
    "stage": "Mega",
    "digiType": ["Holy Knight", "Nerds", "IADA"],
    "attribute": "Vaccine",
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "＜Partition {[WarGreymon] & [MetalGarurumon]}＞\n[When Digivolving] [When Attacking] [Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand or trash without paying its memory cost. If DNA digivolving, add 1 to the number of Digimon cards this effect can play.\n[All Turns] [Once Per Turn] When any of your Digimon with the [Nerds] trait are played, 1 of your opponent's Digimon gets -5000 DP for each of your Digimon with the [Nerds] trait in play until the end of your opponent's turn.\n[All Turns] While you have [Nathan James] in play, all of your Level 5 or higher Digimon with the [Nerds] trait gain ＜Reboot＞.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-104_P1",
    "name": "Omnimon",
    "imgUrl": "/BB1-104_P1.webp",
    "cardType": "Digimon",
    "color": ["White", "Blue", "Red"],
    "cardNumber": "BB1-104",
    "digivolveConditions": [],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nerds] trait: 5 cost",
    "dnaDigivolve": "[DNA Digivolve] [Red]/[Yellow] Lv.6 + [Blue]/[Green] Lv.6\u00a0: Cost 0",
    "stage": "Mega",
    "digiType": ["Holy Knight", "Nerds", "IADA"],
    "attribute": "Vaccine",
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "＜Partition {[WarGreymon] & [MetalGarurumon]}＞\n[When Digivolving] [When Attacking] [Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand or trash without paying its memory cost. If DNA digivolving, add 1 to the number of Digimon cards this effect can play.\n[All Turns] [Once Per Turn] When any of your Digimon with the [Nerds] trait are played, 1 of your opponent's Digimon gets -5000 DP for each of your Digimon with the [Nerds] trait in play until the end of your opponent's turn.\n[All Turns] While you have [Nathan James] in play, all of your Level 5 or higher Digimon with the [Nerds] trait gain ＜Reboot＞.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-104_P2",
    "name": "Omnimon",
    "imgUrl": "/BB1-104_P2.webp",
    "cardType": "Digimon",
    "color": ["White", "Blue", "Red"],
    "cardNumber": "BB1-104",
    "digivolveConditions": [],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nerds] trait: 5 cost",
    "dnaDigivolve": "[DNA Digivolve] [Red]/[Yellow] Lv.6 + [Blue]/[Green] Lv.6\u00a0: Cost 0",
    "stage": "Mega",
    "digiType": ["Holy Knight", "Nerds", "IADA"],
    "attribute": "Vaccine",
    "dp": 15000,
    "playCost": 15,
    "level": 7,
    "mainEffect": "＜Partition {[WarGreymon] & [MetalGarurumon]}＞\n[When Digivolving] [When Attacking] [Once Per Turn] You may play 1 Level 5 or lower Digimon card with the [Nerds] trait from your hand or trash without paying its memory cost. If DNA digivolving, add 1 to the number of Digimon cards this effect can play.\n[All Turns] [Once Per Turn] When any of your Digimon with the [Nerds] trait are played, 1 of your opponent's Digimon gets -5000 DP for each of your Digimon with the [Nerds] trait in play until the end of your opponent's turn.\n[All Turns] While you have [Nathan James] in play, all of your Level 5 or higher Digimon with the [Nerds] trait gain ＜Reboot＞.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  }
]);