// ==========================================
// BEYOND THE BONDS (BB1) & ST01 MONGO UPDATE SCRIPT
// ==========================================

// 1. Array of card numbers to clean up prior to insertion
const cardNumbersToClean = [
  "ST01-01",   // Hopmon
  "ST01-02",   // Salamon
  "ST01-03",   // Gatomon
  "ST01-04",   // Angewomon
  "ST01-05",   // Magnadramon
  "ST01-06",   // Nyabootmon
  "ST01-07",   // Dagger
  "ST01-08",   // Strikedramon
  "ST01-009",  // Cyberdramon
  "ST01-010",  // Darkdramon
  "ST01-11",   // Fujinmon
  "ST01-12",   // Kari Kamiya
  "ST01-13",   // Nico Kärnä
  "ST01-14",   // Erase Claw
  "ST01-15",   // When Dark Meets The Light
  "BB1-035",   // Metatromon (Fixed to BB1-035)
  "BB1-043",   // Lynxmon (Fixed text from Metatromon to Lynxmon)
  "BB1-085"    // Anubismon (Standard + Alt Art)
];

db.card.deleteMany({ cardNumber: { $in: cardNumbersToClean } });

// 2. Insert Updated and New Cards
db.card.insertMany([
  // --- FULL ST01 SET (NIKARI LINE) ---
  {
    "uniqueCardNumber": "ST01-01",
    "name": "Hopmon",
    "imgUrl": "/ST01-01.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-01",
    "digivolveConditions": [],
    "stage": "In-Training",
    "digiType": ["Lesser", "Nikari"],
    "attribute": null,
    "dp": null,
    "playCost": null,
    "level": 2,
    "mainEffect": null,
    "inheritedEffect": "[All Turns] [Once Per Turn] When an opponent's Digimon is deleted, ＜Draw 1＞.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-02",
    "name": "Salamon",
    "imgUrl": "/ST01-02.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-02",
    "digivolveConditions": [{ "color": "Yellow", "level": 2, "cost": 0 }],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[Nikari] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Mammal", "Nikari"],
    "attribute": "Vaccine",
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[On Play] [Start of Your Main Phase] One of your Digimon with the [Nikari] trait may digivolve into a Yellow or Black Digimon card with the [Nikari] trait in your hand with its digivolution cost reduced by 1.",
    "inheritedEffect": "[Your Turn] Your opponent's security Digimon get -3000 DP.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "gusart.22",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-03",
    "name": "Gatomon",
    "imgUrl": "/ST01-03.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-03",
    "digivolveConditions": [{ "color": "Yellow", "level": 3, "cost": 2 }],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Nikari] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Holy Beast", "Nikari"],
    "attribute": "Vaccine",
    "dp": 4000,
    "playCost": 4,
    "level": 4,
    "mainEffect": "[When Digivolving] If you have 1 or fewer Tamers, you may play 1 Tamer card with the [Nikari] trait from your hand without paying its memory cost.",
    "inheritedEffect": "[Your Turn] Your opponent's security Digimon get -3000 DP.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Lacapiart",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-04",
    "name": "Angewomon",
    "imgUrl": "/ST01-04.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-04",
    "digivolveConditions": [{ "color": "Yellow", "level": 4, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[Nikari] trait: 3 cost",
    "stage": "Ultimate",
    "digiType": ["Archangel", "Nikari"],
    "attribute": "Vaccine",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "＜Alliance＞\n[On Play] [When Digivolving] [When Attacking] 1 of your opponent's Digimon gets -4000 DP until the end of their turn.\n[End of Your Turn] This Digimon and 1 of your other Digimon with the [Nikari] trait in play may DNA digivolve into a Digimon card with the [Nikari] trait in your hand.",
    "inheritedEffect": "＜Alliance＞",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-05",
    "name": "Magnadramon",
    "imgUrl": "/ST01-05.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-05",
    "digivolveConditions": [{ "color": "Yellow", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Nikari] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Holy Dragon", "Four Great Dragons", "Nikari"],
    "attribute": "Vaccine",
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "＜Barrier＞ ＜Ascension＞\n[On Play] [When Digivolving] 1 of your other Digimon with the [Nikari] trait may digivolve into a Level 5 or lower Black Digimon card with the [Nikari] trait in your hand without paying its memory cost. Your opponent's Digimon effects do not affect your Black Digimon with the [Nikari] trait until the end of their turn.\n[When Digivolving] [End of Attack] If you have 1 or fewer security cards, this Digimon may digivolve into [Nyabootmon] in your hand with its digivolution cost reduced by 1.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-06",
    "name": "Nyabootmon",
    "imgUrl": "/ST01-06.webp",
    "cardType": "Digimon",
    "color": ["Yellow"],
    "cardNumber": "ST01-06",
    "digivolveConditions": [{ "color": "Yellow", "level": 6, "cost": 4 }],
    "specialDigivolve": "[Digivolve] from Lv.6 w/[Nikari] trait: 4 cost",
    "stage": "Mega",
    "digiType": ["Puppet", "Nikari"],
    "attribute": "Vaccine",
    "dp": 14000,
    "playCost": 14,
    "level": 7,
    "mainEffect": "＜Piercing＞ ＜Engage＞\n[When Digivolving] This Digimon may unsuspend.\n[When Digivolving] [When Attacking] [Once Per Turn] If you have a [Kari Kamiya] in play, trash your opponent's top security card.\n[End of Attack] If you have 2 or fewer security cards, ＜Recovery +1 (Deck)＞. Then, 1 of your opponent's Digimon gets -6000 DP, and all of your opponent's Digimon get -3000 DP for each card in your security stack until the end of their turn.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-07",
    "name": "Dagger",
    "imgUrl": "/ST01-07.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-07",
    "digivolveConditions": [{ "color": "Black", "level": 2, "cost": 0 }],
    "specialDigivolve": "[Digivolve] from Lv.2 w/[Nikari] trait: 0 cost",
    "stage": "Rookie",
    "digiType": ["Mini Dragon", "Nikari"],
    "attribute": "Vaccine",
    "dp": 2000,
    "playCost": 3,
    "level": 3,
    "mainEffect": "[On Play] [When Moving] 1 of your Digimon with the [Nikari] trait gets +4000 DP until the end of your opponent's turn.\n[Your Turn] If your opponent has a Digimon with 10000 DP or more, by placing 1 [Nico Kärnä] from your hand or battle area under this Digimon as its bottom digivolution card, this Digimon may digivolve into [Fujinmon] in your hand for a digivolution cost of 4, ignoring digivolution requirements. When this Digimon would digivolve into [Fujinmon] by this effect, this Digimon cannot have its DP reduced by your opponent's effects until the end of your opponent's turn.\n[Rule] Treat this card as having the name [Monodramon]",
    "inheritedEffect": "[End of Attack] [Once Per Turn] If this Digimon's attack target was an opponent's Digimon, ＜Draw 1＞.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-08",
    "name": "Strikedramon",
    "imgUrl": "/ST01-08.webp",
    "cardType": "Digimon",
    "color": ["Blue"],
    "cardNumber": "ST01-08",
    "digivolveConditions": [{ "color": "Blue", "level": 3, "cost": 2 }],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Nikari] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Dragonkin", "Nikari"],
    "attribute": "Vaccine",
    "dp": 5000,
    "playCost": 5,
    "level": 4,
    "mainEffect": "[Main] [Once Per Turn] You may play or use 1 card with the [Nikari] trait from your hand or trash with its play cost or use cost reduced by 2.",
    "inheritedEffect": "[Your Turn] If you have Tamers in play with 2 or more different names, this Digimon gets +3000 DP.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-009",
    "name": "Cyberdramon",
    "imgUrl": "/ST01-009.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-009",
    "digivolveConditions": [{ "color": "Black", "level": 4, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.4 w/[Nikari] trait: 3 cost",
    "stage": "Ultimate",
    "digiType": ["Cyborg", "Nikari"],
    "attribute": "Vaccine",
    "dp": 7000,
    "playCost": 7,
    "level": 5,
    "mainEffect": "＜Collision＞\n[On Play] [When Digivolving] You may play 1 [Nico Kärnä] Tamer card from your hand without paying its memory cost.\n[All Turns] When one of your [Kari Kamiya] Tamers or Level 5 or higher Yellow Digimon with the [Nikari] trait would be deleted, this Digimon can digivolve into [Darkdramon] in your hand without paying its digivolution cost. If this Digimon digivolves by this effect, that Tamer or Digimon does not leave the field.",
    "inheritedEffect": "[When Attacking] [Once Per Turn] ＜De-Digivolve 1＞ 1 of your opponent's Digimon.",
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-010",
    "name": "Darkdramon",
    "imgUrl": "/ST01-010.webp",
    "cardType": "Digimon",
    "color": ["Black"],
    "cardNumber": "ST01-010",
    "digivolveConditions": [{ "color": "Black", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Nikari] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Cyborg", "Nikari"],
    "attribute": "Virus",
    "dp": 12000,
    "playCost": 12,
    "level": 6,
    "mainEffect": "＜Collision＞ ＜Reboot＞ ＜Blocker＞\n[When Digivolving] ＜De-Digivolve 2＞ 1 of your opponent's Digimon. Then, if digivolved by a card with the [Nikari] trait's effect, your opponent can't trash the digivolution cards of 1 of your Yellow and 1 of your Black Digimon with the [Nikari] trait until the end of their turn.\n[All Turns] [Once Per Turn] When this Digimon deletes an opponent's Digimon in battle, this Digimon may unsuspend.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-11",
    "name": "Fujinmon",
    "imgUrl": "/ST01-11.webp",
    "cardType": "Digimon",
    "color": ["Green"],
    "cardNumber": "ST01-11",
    "digivolveConditions": [{ "color": "Green", "level": 5, "cost": 3 }],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[Nikari] trait: 3 cost",
    "stage": "Mega",
    "digiType": ["Cyborg", "Nikari"],
    "attribute": "Vaccine",
    "dp": 13000,
    "playCost": 13,
    "level": 6,
    "mainEffect": "＜Blocker＞ ＜Vortex＞ ＜Reboot＞\n[When Digivolving] Suspend 1 of your opponent's Digimon or Tamers. Then, unsuspend 1 of your Digimon.\n[When Attacking] [Once Per Turn] This Digimon may battle 1 of your opponent's Digimon.\n[Your Turn] [Once Per Turn] When this Digimon deletes an opponent's Digimon in battle, if this Digimon has [Nico Kärnä] in its digivolution cards, activate 1 of this Digimon's [When Digivolving] effects.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-12",
    "name": "Kari Kamiya",
    "imgUrl": "/ST01-12.webp",
    "cardType": "Tamer",
    "color": ["Yellow"],
    "cardNumber": "ST01-12",
    "digivolveConditions": [],
    "digiType": ["Nikari"],
    "playCost": 3,
    "mainEffect": "[Start of Your Main Phase] If you have a Digimon in play, gain 1 memory.\n[All Turns] When one of your Digimon digivolves into a Black Digimon with the [Nikari] trait, you may suspend this Tamer to give that Digimon ＜Barrier＞ until the end of your turn.",
    "securityEffect": "[Security] Play this card without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-13",
    "name": "Nico Kärnä",
    "imgUrl": "/ST01-13.webp",
    "cardType": "Tamer",
    "color": ["Yellow"],
    "cardNumber": "ST01-13",
    "digivolveConditions": [],
    "digiType": ["Nikari"],
    "playCost": 3,
    "mainEffect": "[Start of Your Main Phase] If your opponent has a Digimon in play, gain 1 memory.\n[All Turns] When one of your Digimon digivolves into a Yellow Digimon with the [Nikari] trait, you may suspend this Tamer to give that Digimon ＜Blocker＞ until the end of your opponent's turn.",
    "inheritedEffect": "＜Piercing＞",
    "securityEffect": "[Security] Play this card without paying the cost.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-14",
    "name": "Erase Claw",
    "imgUrl": "/ST01-14.webp",
    "cardType": "Option",
    "color": ["Blue"],
    "cardNumber": "ST01-14",
    "digivolveConditions": [],
    "digiType": ["Nikari"],
    "playCost": 6,
    "mainEffect": "＜Use Req. ([Nikari] trait)＞\nWhen this card would be used, if you have a Digimon with [Cyberdramon] in its name and the [Nikari] trait in play, reduce the cost by 2.\n[Main] Choose 1 of the following effects:\n• Delete 1 of your opponent's Level 5 or lower Digimon.\n• Delete 1 of your opponent's Level 6 or higher Digimon. If you do, delete 1 of your Tamers named [Kari Kamiya].",
    "securityEffect": "[Security] Add this card to your hand.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "ST01-15",
    "name": "When Dark Meets The Light",
    "imgUrl": "/ST01-15.webp",
    "cardType": "Option",
    "color": ["Blue"],
    "cardNumber": "ST01-15",
    "digivolveConditions": [],
    "digiType": ["Nikari"],
    "playCost": 3,
    "mainEffect": "＜Use Req. ([Nikari] trait)＞\n[Main] Reveal the top 3 cards of your deck. Add 1 card with the [Nikari] trait from among them to your hand. Return the remaining cards to the bottom of your deck in any order. Then, place this card in the battle area.\n[Main] ＜Delay＞\n• You may play 1 Tamer card with the [Nikari] trait from your hand with its play cost reduced by 3.",
    "securityEffect": "[Security] Activate this card's [Main] effects.",
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- BB1-035 METATROMON (FIXED LOCATION) ---
  {
    "uniqueCardNumber": "BB1-035",
    "name": "Metatromon",
    "imgUrl": "/BB1-035.webp",
    "cardType": "Digimon",
    "color": ["Blue", "Black"],
    "cardNumber": "BB1-035",
    "digivolveConditions": [
      { "color": "Blue", "level": 5, "cost": 5 },
      { "color": "Black", "level": 5, "cost": 5 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.5 w/[IADA] trait: 4 cost",
    "stage": "Mega",
    "digiType": ["Machine", "IADA"],
    "attribute": "Vaccine",
    "dp": 13000,
    "playCost": 13,
    "level": 6,
    "mainEffect": "＜Blocker＞ ＜Decode ([MetalMamemon])＞\nWhen any of your [MetalMamemon] would digivolve into this Digimon card, reduce the digivolution cost by 1 for every 2 of your [IADA] trait Tamers with different names.\n[When Digivolving] [When Attacking] [Once Per Turn] You may play 1 Tamer card with the [IADA] trait from your hand or trash without paying the cost. This effect cannot play a Tamer card with the same name as any of your Tamers in play. Then, if you have [Director Watanabe] in play, return 1 of your opponent's Digimon with the lowest play cost to the bottom of their deck.\n[All Turns] [Once Per Turn] When any of your Tamers with the [IADA] trait are played or suspend, 1 of your opponent's Digimon cannot suspend until the end of your opponent's turn.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- BB1-043 LYNXMON (CORRECTED FROM IMAGE) ---
  {
    "uniqueCardNumber": "BB1-043",
    "name": "Lynxmon",
    "imgUrl": "/BB1-043.webp",
    "cardType": "Digimon",
    "color": ["Yellow", "Red"],
    "cardNumber": "BB1-043",
    "digivolveConditions": [
      { "color": "Yellow", "level": 3, "cost": 3 },
      { "color": "Red", "level": 3, "cost": 3 }
    ],
    "specialDigivolve": "[Digivolve] from Lv.3 w/[Arena] trait: 2 cost",
    "stage": "Champion",
    "digiType": ["Beast", "Arena"],
    "attribute": "Free",
    "dp": 6000,
    "playCost": 6,
    "level": 4,
    "mainEffect": "＜Armor Purge＞ ＜Barrier＞\n[End of Attack] [Once Per Turn] This Digimon may digivolve into a Digimon card in your hand with the [Arena], [Angel], or [Holy Beast] trait with its digivolution cost reduced by 1.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },

  // --- ANUBISMON FIX (BB1-085 STANDARD + ALT ART) ---
  {
    "uniqueCardNumber": "BB1-085",
    "name": "Anubismon",
    "imgUrl": "/BB1-085.webp",
    "cardType": "Digimon",
    "color": ["Purple"],
    "cardNumber": "BB1-085",
    "digivolveConditions": [{ "color": "Purple", "level": 5, "cost": 3 }],
    "stage": "Mega",
    "digiType": ["Shaman"],
    "attribute": "Vaccine",
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "[When Digivolving] You may play 1 Level 4 or lower Digimon card from your trash without paying its memory cost.\n[All Turns] All of your Digimon played from the trash gain ＜Rush＞ for the turn.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  },
  {
    "uniqueCardNumber": "BB1-085_P1",
    "name": "Anubismon",
    "imgUrl": "/BB1-085_P1.webp",
    "cardType": "Digimon",
    "color": ["Purple"],
    "cardNumber": "BB1-085",
    "digivolveConditions": [{ "color": "Purple", "level": 5, "cost": 3 }],
    "stage": "Mega",
    "digiType": ["Shaman"],
    "attribute": "Vaccine",
    "dp": 11000,
    "playCost": 11,
    "level": 6,
    "mainEffect": "[When Digivolving] You may play 1 Level 4 or lower Digimon card from your trash without paying its memory cost.\n[All Turns] All of your Digimon played from the trash gain ＜Rush＞ for the turn.",
    "inheritedEffect": null,
    "securityEffect": null,
    "restrictions": { "english": "Unrestricted", "japanese": "Unrestricted" },
    "illustrator": "Beyond The Bonds",
    "_class": "com.github.wekaito.backend.models.Card"
  }
]);